#!/usr/bin/env python3
"""Stage33-05: identify the q1 obstruction with Hochschild--Serre d2.

This closes the last arithmetic-descent gap left by q1_ns_lift_parity.py.

Formal input.
------------
Let X=K_c over Q and let G=<ct> be the order-two subgroup generated by
sqrt(2)-conjugation.  Since Xbar is a K3 surface, Pic(Xbar)=NS(Xbar) is
free abelian.  Kummer therefore gives a short exact sequence of G-modules

  0 -> Pic(Xbar)/2 -> H^2_et(Xbar,mu_2) -> Br(Xbar)[2] -> 0.        (K)

For an invariant geometric 2-torsion Brauer class beta, choose a Kummer lift
c.  Its Galois defect sigma(c)-c is a 1-cocycle in Pic/2.  The standard
Kummer/Leray double-complex chase identifies the Hochschild--Serre differential

  d2^{0,2}(beta) in H^2(G,Pic(Xbar))

with the Bockstein of this Pic/2 defect for

  0 -> Pic --2--> Pic -> Pic/2 -> 0.                              (B)

Compatibility with the Creutz--Viray finite presentation is not an extra
assumption here.  Their gamma is explicitly the corestriction quaternion/cup
product defining the mu_2 lift; Theorem 2.5 makes the presentation Galois
-equivariant, while Creutz--Viray, Two torsion..., Remark 3.1, Proposition 3.2,
and Lemmas 3.4--3.5 compute the corresponding Pic/divisor/Brauer cocycles and
identify them with the Hochschild--Serre edge construction (up to the harmless
sign, irrelevant at 2-torsion).  Thus the already certified presentation defect

  ct(q1)-q1 = J1

is precisely the Kummer defect in Pic/2.  q1_ns_lift_parity.py materializes an
integral ct-invariant lift

  D = E_[0:1:0:-1:0:1] + Cb,
  Cb: i*A1+B1=i*A2+B2=i*A3+B3=0,

and proves D is not in N Pic=(1+ct)Pic by pairing with a ct-invariant conic T:
D.T=1.  The normalized C2 Bockstein is then immediate: lift the nontrivial
1-cocycle value D mod 2 by D.  Its coboundary at (ct,ct) is 2D, so after
_dividing by 2_ the Bockstein 2-cocycle has value D.  Therefore

  d2(q1)|_G = [D] != 0 in H^2(G,Pic)=Pic^G/N Pic.

A class with nonzero restricted d2 cannot have zero global d2, hence q1 does
not descend to Br(X).  The other quotient basis class J2 has already been
materialized as an explicit Q-defined unramified corestriction algebra.  Since
Br(Xbar)[2]^G_Q has basis [J2,q1], the exact Q-surviving geometric 2-torsion
dimension is therefore one.
"""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent

# Load the exact predecessor certificates produced earlier in this workflow.
pair = json.loads((ROOT / "xalpha-pair-galois-repair.json").read_text())
front = json.loads((ROOT / "descent-presentation-cocycle.json").read_text())
j2 = json.loads((ROOT / "j2-arithmetic-descent.json").read_text())
ns = json.loads((ROOT / "q1-ns-lift-cyclic-parity.json").read_text())

assert pair["full_pair_galois_action_exact"] is True
assert pair["geometric_Br2_GQ_invariant_dimension"] == 2
assert pair["explicit_brauer_quotient_basis"] == ["J2", "q1"]
assert front["presentation_connecting_cocycle"]["q1"]["ct"] == "J1"
assert front["presentation_connecting_cocycle"]["J2"]["ct"] == "0"
assert j2["J2_Q_descent_certified"] is True
assert j2["Q_defined_arithmetic_representative_materialized"] is True
assert ns["J1_integral_NS_lift_materialized"] is True
assert ns["D_ct_invariant"] is True
assert ns["D_test_intersection"] == 1
assert ns["D_nonzero_in_H2_C2_Pic"] is True

# -------------------------------------------------------------------------
# Normalized C2 cochain calculation of the Bockstein.
# -------------------------------------------------------------------------
# We only need the subgroup generated by g=ct.  The Picard class D is kept as
# a symbolic free generator for this cochain calculation; nontriviality of its
# H^2 class is independently certified by the odd invariant intersection in
# q1_ns_lift_parity.py.
G = (0, 1)  # 0=e, 1=g; addition is mod 2

# Integral lift J of the Pic/2-valued normalized 1-cocycle j:
# J(e)=0, J(g)=D.  Coefficients below are integers multiplying D.
J = {0: 0, 1: 1}


def act(g, coeff):
    # D is g-invariant.
    return coeff


def coboundary_J(g, h):
    # additive inhomogeneous differential: g J(h) - J(gh) + J(g)
    return act(g, J[h]) - J[(g + h) & 1] + J[g]

# Because j=J mod 2 is a cocycle, dJ is divisible by 2.  The Bockstein is dJ/2.
dJ = {(g, h): coboundary_J(g, h) for g in G for h in G}
assert dJ == {(0,0):0, (0,1):0, (1,0):0, (1,1):2}
assert all(v % 2 == 0 for v in dJ.values())
bockstein = {k: v // 2 for k, v in dJ.items()}
assert bockstein == {(0,0):0, (0,1):0, (1,0):0, (1,1):1}

# Verify the normalized 2-cocycle identity directly for all triples.
def b(g, h):
    return bockstein[(g, h)]

for g in G:
    for h in G:
        for k in G:
            # d b(g,h,k)=g b(h,k)-b(gh,k)+b(g,hk)-b(g,h)
            db = act(g, b(h,k)) - b((g+h)&1,k) + b(g,(h+k)&1) - b(g,h)
            assert db == 0

# H^2(C2,Pic)=Pic^g/N Pic.  The predecessor's invariant odd pairing proves
# [D] is not a norm, hence this cocycle is nonzero in H^2.
D_is_norm = ns["D_is_cyclic_norm"]
assert D_is_norm is False
restricted_d2_nonzero = True

# Restriction is functorial.  If the global HS d2 vanished, every subgroup
# restriction would vanish, contradicting the computed C2 class.
global_d2_q1_nonzero = restricted_d2_nonzero
q1_Q_descent = False

# The invariant space is exactly 2D with basis J2,q1.  J2 has zero obstruction
# by its explicit Q-class; q1 and q1+J2 have the same nonzero d2.  Kernel=span J2.
Q_surviving_dimension = 1

cert = {
    "schema": "STAGE33_05_Q1_HS_D2_BOCKSTEIN_V1",
    "source_lock": {
        "kummer": "Stacks Project tag 03PK, Lemma 59.28.1 and its long exact sequence",
        "leray": "Stacks Project tag 03QA / Proposition 59.54.2",
        "cv_surface": "Creutz--Viray, On Brauer groups of double covers of ruled surfaces, Theorem 2.5 and Theorem I",
        "cv_curve_hs": "Creutz--Viray, Two torsion in the Brauer group of a hyperelliptic curve, Remark 3.1 and Proposition 3.2",
        "cv_curve_chain": "same paper, Lemmas 3.4--3.5: divisor coboundary and corestriction/cup-product cocycle",
        "pic_torsion_free": "K3 Picard group is Neron--Severi and torsion-free; Stage33/Testa--Stoll PicK rank-20 lattice source lock",
    },
    "formal_compatibility_statement": "For invariant beta in Br(Xbar)[2], HS d2(beta) is the Bockstein of its Kummer Pic/2 defect; the CV presentation defect agrees with that Kummer defect because gamma is the explicit corestriction cup-product lift and the CV cocycle comparison is Galois-equivariant.",
    "effective_subgroup": "C2=<ct>",
    "geometric_brauer_basis": ["J2", "q1"],
    "q1_kummer_defect": "J1 = D mod 2",
    "D_integral_NS_lift": ns["J1_integral_NS_lift"],
    "D_ct_invariant": True,
    "D_test_intersection": ns["D_test_intersection"],
    "D_nonzero_in_H2_C2_Pic": True,
    "normalized_integral_1cochain_coefficients": {"e":0, "ct":1},
    "integral_coboundary_coefficients_on_D": {
        "e,e":0, "e,ct":0, "ct,e":0, "ct,ct":2
    },
    "bockstein_2cocycle_coefficients_on_D": {
        "e,e":0, "e,ct":0, "ct,e":0, "ct,ct":1
    },
    "HS_d2_restricted_to_C2_equals_D_class": True,
    "HS_d2_q1_restriction_nonzero": True,
    "HS_d2_q1_global_nonzero": global_d2_q1_nonzero,
    "q1_Q_descent_certified": True,
    "q1_Q_descent": q1_Q_descent,
    "J2_Q_descent_certified": True,
    "J2_Q_descent": True,
    "geometric_Br2_GQ_invariant_dimension": 2,
    "Q_relevant_surviving_dimension_certified": True,
    "Q_relevant_surviving_dimension": Q_surviving_dimension,
    "Q_surviving_geometric_Br2_basis": ["J2"],
    "all_stage33_05_descent_unknowns_resolved": True,
    "next_exact_leaf": "L33-05-HOSTILE-AUDIT-AND-CLOSURE-EVIDENCE",
    "theorem_credit": False,
    "endpoint_credit": False,
    "perfect_cuboid_nonexistence_claim": False,
}
canonical = json.dumps(cert, sort_keys=True, separators=(",", ":")).encode()
cert["canonical_sha256"] = hashlib.sha256(canonical).hexdigest()
(ROOT / "q1-hs-d2-bockstein.json").write_text(
    json.dumps(cert, indent=2, sort_keys=True) + "\n", encoding="utf-8"
)
print(json.dumps(cert, indent=2, sort_keys=True))
