#!/usr/bin/env python3
"""Stage33-05 exact NS lift and cyclic non-norm parity certificate for q1.

The CV-presentation cocycle gives ct(q1)-q1=J1.  The x-alpha repair expressed
J1 as the difference (sum mod 2) of two rational points on the generic ruled
fiber: s=1 and s=-i(t-i)/(t+i).  This checker closes those sections in K_c and
materializes an integral ct-invariant divisor lift D of that J1 relation.

It then proves D is not a cyclic norm in Pic(K_cbar) for the C2 generated by
ct, using an invariant test conic with odd intersection.  Thus D represents a
nonzero class in H^2(C2,Pic)=Pic^ct/N Pic.

Firewall: the remaining step is to source-lock/derive that the Hochschild--
Serre d2(q1), restricted to this C2, is represented by this particular NS lift
(rather than merely the CV-presentation connecting class).  This checker does
not make that identification and therefore does not yet declare q1 non-descending.
"""
import hashlib
import json
from pathlib import Path
import sympy as sp

ROOT = Path(__file__).resolve().parent
t = sp.symbols("t")
i = sp.I

# Stage29 affine ruled map, v1=v2=1.
s = -i*(t-i)/(t+i)
A1 = sp.factor((1-t**2)*(1-s**2))
A2 = sp.factor(2*s*(1-t**2))
A3 = sp.factor(2*t*(1-s**2))
B2 = sp.factor((1+t**2)*(1-s**2))
B3 = sp.factor((1+s**2)*(1-t**2))
F = sp.factor(t**2*(1-s**2)**2+s**2*(1-t**2)**2)
assert sp.simplify(F + (t-1)**4*(t+1)**4/(t+i)**4) == 0
w = i*(t**2-1)**2/(t+i)**2
B1 = sp.factor(2*w)

# Scale the projective coordinates to the simple conic parametrization.
scale = sp.cancel((t+i)**2/(2*(t**2-1)))
coords = [sp.factor(scale*x) for x in (A1,A2,A3,B1,B2,B3)]
target = [-(t**2-1), i*(t**2+1), 2*t, i*(t**2-1), t**2+1, -2*i*t]
assert all(sp.simplify(x-y)==0 for x,y in zip(coords,target))

# K_c equations and the all-plus branch conic Cb.
x1,x2,x3,y1,y2,y3 = sp.symbols("A1 A2 A3 B1 B2 B3")
K_eqs = [x1**2+x2**2-y3**2, x2**2+x3**2-y1**2, x1**2+x3**2-y2**2]
subs_curve = dict(zip((x1,x2,x3,y1,y2,y3),target))
assert all(sp.simplify(f.subs(subs_curve))==0 for f in K_eqs)
Cb_eqs = [i*x1+y1, i*x2+y2, i*x3+y3]
assert all(sp.simplify(f.subs(subs_curve))==0 for f in Cb_eqs)

# The chosen s=1 point, with w=-(1-t^2), contracts to singular P0.
P0 = [0,1,0,-1,0,1]
assert all(sp.simplify(f.subs(dict(zip((x1,x2,x3,y1,y2,y3),P0))))==0 for f in K_eqs)
# Jacobian rank <3 confirms singularity of the codimension-3 complete intersection.
JK_P0 = sp.Matrix([[sp.diff(f,x).subs(dict(zip((x1,x2,x3,y1,y2,y3),P0))) for x in (x1,x2,x3,y1,y2,y3)] for f in K_eqs])
assert JK_P0.rank() < 3

# Hence one explicit integral lift of the J1 relation is
# D = E_P0 + Cb on the minimal resolution. Both are ct-invariant: ct is the
# sqrt(2)-conjugation and these defining equations use only Q(i).
D_components = ["E_[0:1:0:-1:0:1]", "Cb: i*A1+B1=i*A2+B2=i*A3+B3=0"]

# Q-defined nonbranch test conic T in the first C1sK orbit.
T_eqs = [x1, x2+y3, x3-y2]
Pint = [0,1,-i,0,-i,-1]
subP = dict(zip((x1,x2,x3,y1,y2,y3),Pint))
assert all(sp.simplify(f.subs(subP))==0 for f in K_eqs+Cb_eqs+T_eqs)
# P0 is not on T, so E_P0.T=0 after resolution.
subP0 = dict(zip((x1,x2,x3,y1,y2,y3),P0))
assert any(sp.simplify(f.subs(subP0))!=0 for f in T_eqs)

# Exact transversality at Pint. For projective tangent spaces, cone tangent
# dimensions are 3 for K and 2 for each conic; the combined tangent constraints
# have nullity 1 (only the radial direction), so Cb.T=1.
vars6 = (x1,x2,x3,y1,y2,y3)
JK = sp.Matrix([[sp.diff(f,x).subs(subP) for x in vars6] for f in K_eqs])
JCb = sp.Matrix([[sp.diff(f,x).subs(subP) for x in vars6] for f in Cb_eqs])
JT = sp.Matrix([[sp.diff(f,x).subs(subP) for x in vars6] for f in T_eqs])
assert JK.rank() == 3
assert JK.col_join(JCb).rank() == 4
assert JK.col_join(JT).rank() == 4
assert JK.col_join(JCb).col_join(JT).rank() == 5
Cb_dot_T = 1
E_dot_T = 0
D_dot_T = Cb_dot_T + E_dot_T
assert D_dot_T == 1

# Cyclic group cohomology: H^2(C2,Pic)=Pic^ct/N Pic, N=1+ct.
# If D=N(E), then for ct-invariant T:
#   D.T=(E+ct(E)).T=E.T+E.ct^{-1}(T)=2(E.T),
# contradiction to D.T=1. Thus D is not a norm.
D_ct_invariant = True
T_ct_invariant = True
D_is_cyclic_norm = False
D_H2_class_nonzero = True

cert = {
    "schema":"STAGE33_05_Q1_NS_LIFT_CYCLIC_PARITY_V1",
    "source_lock":{
        "ruled_map":"stages/stage29/29-15/k3-ruled2-audit-execution.md",
        "xalpha_relation":"xalpha_pair_galois_repair.py: J1=xalpha(mobius)+xalpha(s=1)",
        "testa_stoll":"MichaelStollBayreuth/Verification@51233ed5ef2bf228fac9416c66db9adc0ebcaadd, Cuboids/cuboids.magma: C1sK/branch conics and intersection pairing",
        "cyclic_cohomology":"H^2(C2,M)=M^sigma/N(M)",
    },
    "effective_generator":"ct: sqrt(2)->-sqrt(2), i fixed",
    "presentation_cocycle":"ct(q1)-q1=J1",
    "mobius_section":"s=-i*(t-i)/(t+i)",
    "mobius_closure":D_components[1],
    "s1_closure":D_components[0],
    "J1_integral_NS_lift":D_components,
    "J1_integral_NS_lift_materialized":True,
    "D_ct_invariant":D_ct_invariant,
    "test_conic":"A1=0, A2+B3=0, A3-B2=0",
    "test_conic_ct_invariant":T_ct_invariant,
    "branch_conic_test_intersection":Cb_dot_T,
    "exceptional_test_intersection":E_dot_T,
    "D_test_intersection":D_dot_T,
    "intersection_is_odd":True,
    "D_is_cyclic_norm":D_is_cyclic_norm,
    "D_nonzero_in_H2_C2_Pic":D_H2_class_nonzero,
    "HS_d2_identified_with_D":False,
    "q1_descent_obstruction_accounted":False,
    "q1_declared_nondescending":False,
    "Q_relevant_surviving_dimension_certified":False,
    "next_exact_leaf":"L33-05-Q1-IDENTIFY-HS-D2-WITH-EXPLICIT-NS-LIFT-D",
    "theorem_credit":False,
    "endpoint_credit":False,
}
canonical=json.dumps(cert,sort_keys=True,separators=(",",":")).encode()
cert["canonical_sha256"]=hashlib.sha256(canonical).hexdigest()
(ROOT/"q1-ns-lift-cyclic-parity.json").write_text(json.dumps(cert,indent=2,sort_keys=True)+"\n")
print(json.dumps(cert,indent=2,sort_keys=True))
