#!/usr/bin/env python3
from __future__ import annotations

import json
import subprocess
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
CERT=ROOT/'stages/stage36/36-09CU/bt-kummer-monomial-brauer-secondary-preflight.json'
CT=ROOT/'stages/stage36/36-09CT/bt-pointwise-local-tate-pairing-required-place-preflight.json'
CM=ROOT/'stages/stage36/36-09CM/bt-global-kummer-class-localization-adapter-preflight.json'
PW07=ROOT/'docs/arsenal/cards/provisional/S33-PW07.md'
PW08=ROOT/'docs/arsenal/cards/provisional/S33-PW08.md'
LIT=ROOT/'docs/arsenal/lit-wf02-global-h1-localization-reciprocity-contract.json'
BASE='d5545b32e6b3088bca53318998d434f2745b03e9'
CT_HEAD='562e64f8f4ea64f420a7970a03119d0029d70a10'
LOCKS={
    CERT:'cb92adb9b0025e8cef8554a2c30dc6777b8e2835',
    CT:'923ff0bfa93997bc935f280b274143377aafedde',
    CM:'06c3e6d1fcc2453dc44b84d50896abdc6a1658d7',
    PW07:'7f1337858bc6f9006e101d810dd72e67aef534fd',
    PW08:'c9e13a917811581578f833ea93619d85f717be6d',
    LIT:'6fc62623ee59b4aaf1fc053ad42df2dcbba0855b',
}

def git(*a:str)->str:
    return subprocess.check_output(['git',*a],cwd=ROOT,text=True).strip()

def blob(p:Path)->str:
    return git('hash-object',str(p.relative_to(ROOT)))

def add(u,v):
    return tuple(a^b for a,b in zip(u,v))

def reduce_monomial(mask:int, coeffs:list[tuple[int,...]])->tuple[int,...]:
    z=(0,0,0,0)
    for i,c in enumerate(coeffs):
        if (mask>>i)&1:
            z=add(z,c)
    return z

def main()->None:
    for p,h in LOCKS.items(): assert blob(p)==h,(p,blob(p),h)
    subprocess.check_call(['git','merge-base','--is-ancestor',BASE,'HEAD'],cwd=ROOT)
    subprocess.check_call(['git','merge-base','--is-ancestor',CT_HEAD,'HEAD'],cwd=ROOT)

    c=json.loads(CERT.read_text()); ct=json.loads(CT.read_text()); cm=json.loads(CM.read_text()); lit=json.loads(LIT.read_text())
    assert c['base_main_sha']==BASE
    assert c['batch_parent']=={
        'pr':1712,
        '36_09CT_exact_green_head':CT_HEAD,
        '36_09CT_exact_head_ci':'34192760298/101954018281',
        'promotion_replay_ci':'34192879886/101954365854'
    }
    assert ct['structural_diagnosis']['failure_mode']=='SELF_TRIVIALIZATION_ON_THE_TORSOR_IT_CLASSIFIES'
    assert ct['construction_boundary']['first_missing_obligation']=='BT_NONTRIVIAL_ON_RECEIVER_LOCUS_BRAUER_OR_SECONDARY_TORSOR_EVALUATION'
    assert cm['exact_BT_cover_adapter']['five_equations']==[
        'w0^2=(A*B)*y','w1^2=(kappa*A)*(1-y)','w2^2=(rho*A)*(1+y)',
        'w3^2=(kappa*B)*(1-L*y)','w4^2=(rho*B)*(1+L*y)']

    t7=PW07.read_text(); t8=PW08.read_text()
    assert 'TORSOR_BRAUER_INTEGRAL_KERNEL_ADAPTER' in t7
    assert 'exact common cocycle' in t7
    assert 'actual transition function/divisor/Cartier data' in t7
    assert 'GERSTEN_CONNECTING_LOCALIZATION_ADAPTER' in t8
    assert 'PW08 promotes the construction/audit protocol, not that value' in t8
    assert 'calling the Hilbert product formula a contradiction' in lit['do_not_use_for']

    a=c['asset_discovery_result']
    assert a['S33_PW07_reusable_contract_found'] is True
    assert a['S33_PW07_direct_BT_representative_found'] is False
    assert a['S33_PW08_protocol_reusable'] is True
    assert a['S33_PW08_concrete_map_transferred_to_BT'] is False
    assert a['existing_BT_nontrivial_secondary_or_Brauer_evaluation_found'] is False
    assert a['repository_search_miss_is_mathematical_nonexistence_claim'] is False

    km=c['five_root_kummer_monomial_group']
    assert km['base_functions']==['g0=y','g1=1-y','g2=1+y','g3=1-L*y','g4=1+L*y']
    assert km['twist_coefficients']==['c0=A*B','c1=kappa*A','c2=rho*A','c3=kappa*B','c4=rho*B']
    assert km['all_32_root_function_parity_patterns_covered'] is True

    # Coefficient squareclasses in the fixed basis (A,B,kappa,rho).
    coeffs=[
        (1,1,0,0), # AB
        (1,0,1,0), # kappa A
        (1,0,0,1), # rho A
        (0,1,1,0), # kappa B = AB * kappa A
        (0,1,0,1), # rho B   = AB * rho A
    ]
    assert coeffs[3]==add(coeffs[0],coeffs[1])
    assert coeffs[4]==add(coeffs[0],coeffs[2])

    # Exhaust all 32 monomial parity patterns. On a receiver lift [g_i]=[c_i],
    # hence every monomial has a fixed global coefficient squareclass and no
    # residual point-coordinate bit.
    table={mask:reduce_monomial(mask,coeffs) for mask in range(32)}
    assert len(table)==32
    assert all(len(v)==4 for v in table.values())
    assert len(set(table.values()))==8  # the five roots are generated by the three CM twist coordinates

    # Exhaust all 32 x 32 symbol parity pairs: each pair reduces to two fixed
    # global coefficient squareclasses. There is no receiver-point variable left.
    reduced_pairs={(table[e],table[f]) for e in range(32) for f in range(32)}
    assert len(reduced_pairs)==64

    q=c['quaternion_family_no_go']
    assert q['point_dependence_survives_on_receiver_locus'] is False
    assert q['adelic_total_for_each_symbol']=='product_v (A_e,B_f)_v=+1 by Hilbert reciprocity for the two fixed global squareclasses.'
    assert q['can_supply_Brauer_Manin_obstruction_on_receiver_locus'] is False
    assert q['can_exclude_fixed_p_branch'] is False
    assert q['can_shrink_candidate_parameters'] is False

    sd=c['structural_diagnosis']
    assert sd['failure_mode']=='KUMMER_MONOMIAL_COLLAPSE_TO_GLOBAL_CONSTANT_SQUARECLASSES_PLUS_RECIPROCITY'
    assert sd['S33_PW07_literal_divisor_cocycle_requirements_remain_missing'] is True
    cb=c['construction_boundary']; rr=c['route_result']
    assert cb['BT_KUMMER_MONOMIAL_QUATERNION_FAMILY_EXHAUSTED_AS_OBSTRUCTION'] is True
    assert cb['BT_NONTRIVIAL_RECEIVER_LOCUS_SECONDARY_EVALUATION_FOUND'] is False
    assert cb['BT_BRAUER_CLASS_WITH_POINT_DEPENDENT_RECEIVER_EVALUATION_FOUND'] is False
    assert cb['BT_POITOU_TATE_local_condition_system_complete'] is False
    assert cb['Stage36_required_place_inventory_complete'] is False
    assert cb['LIT_WF02_applicability_PASS'] is False
    assert cb['new_global_obstruction_obtained'] is False
    assert cb['first_missing_obligation']=='BT_NON_KUMMER_DIVISOR_COCYCLE_OR_SECONDARY_EXTENSION_SOURCE'
    assert rr['route_status']=='NO_GO_FIVE_ROOT_KUMMER_MONOMIAL_BRAUER_FAMILY_RECIPROCITY_TRIVIAL_PIVOT_TO_NON_KUMMER_DIVISOR_COCYCLE'
    assert rr['next_leaf']=='36-09CV_BT_NON_KUMMER_DIVISOR_COCYCLE_BRAUER_SOURCE_PREFLIGHT'
    for k,v in c['scope_firewalls'].items(): assert v is False,(k,v)
    print('36-09CU verified: every quaternion evaluation generated by Q* and the five BT root functions collapses on receiver lifts to fixed global squareclass pairs, so its adelic total is reciprocity-trivial. Non-Kummer divisor/Cech or secondary-extension source is next. No BM/PT/receiver/endpoint credit.')

if __name__=='__main__': main()
