#!/usr/bin/env python3
"""Validate docs/arsenal/index.json and render its compact human catalog."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


HERE = Path(__file__).resolve().parent
INDEX = HERE / "index.json"
CATALOG = HERE / "catalog.md"


def rel_exists(value: str) -> bool:
    return (HERE / value).resolve().exists()


def collect(data: dict) -> tuple[list[dict], list[str]]:
    entries: list[dict] = []
    errors: list[str] = []

    for item in data.get("selectors", []):
        entries.append({**item, "maturity": "FORMAL", "kind": "selector"})
    for item in data.get("formal_router_weapons", []):
        entries.append({**item, "maturity": "FORMAL", "kind": "weapon"})
    for item in data.get("formal_workflows", []):
        entries.append({**item, "maturity": "WORKFLOW", "kind": "workflow", "role": item.get("name", "")})

    retired: dict[str, str] = {}
    for harvest in data.get("provisional_harvests", []):
        for card_id in harvest.get("active_cards", []):
            entries.append({
                "id": card_id,
                "role": harvest.get("card_roles", {}).get(card_id, ""),
                "path": harvest["path"],
                "maturity": "PROVISIONAL",
                "kind": "weapon",
                "source_stage": harvest["source_stage"],
            })
        retired.update(harvest.get("retired_merged_ids", {}))

    ids = [entry["id"] for entry in entries]
    duplicates = sorted({item for item in ids if ids.count(item) > 1})
    if duplicates:
        errors.append(f"duplicate active IDs: {', '.join(duplicates)}")

    active_ids = set(ids)
    for old, successor in sorted(retired.items()):
        if successor not in active_ids:
            errors.append(f"retired ID {old} has missing successor {successor}")

    for entry in entries:
        if not rel_exists(entry["path"]):
            errors.append(f"missing path for {entry['id']}: {entry['path']}")
    for path in data.get("stable_weapon_libraries", []):
        if not rel_exists(path):
            errors.append(f"missing stable library: {path}")
    for path in data.get("superseded_indexes", []):
        if not rel_exists(path):
            errors.append(f"missing historical index: {path}")
    for record in data.get("support_records", []):
        if record.get("class") not in {"FORMAL", "PROVISIONAL", "WORKFLOW", "HISTORICAL", "RETIRED"}:
            errors.append(f"invalid support-record class: {record.get('class')}")
        if not rel_exists(record["path"]):
            errors.append(f"missing support record: {record['path']}")

    contract = data.get("registry_contract", {})
    if not contract.get("canonical_machine_registry"):
        errors.append("registry_contract.canonical_machine_registry must be true")
    if contract.get("human_catalog") != CATALOG.name:
        errors.append("registry_contract.human_catalog must name catalog.md")

    return entries, errors


def link(path: str) -> str:
    return f"[{path}]({path})"


def source_stage(entry: dict) -> str:
    if entry.get("source_stage"):
        return entry["source_stage"]
    prefix = entry["id"].split("-", 1)[0]
    if prefix.startswith("S") and prefix[1:].isdigit():
        return f"Stage{prefix[1:]}"
    return "—"


def render(data: dict, entries: list[dict]) -> str:
    lines = [
        "# Arsenal catalog",
        "",
        "<!-- Generated by sync_arsenal_catalog.py; edit index.json, not this file. -->",
        "",
        "This is the compact human view of [`index.json`](index.json), the sole machine-readable registry. Card contracts remain in the linked stable source files.",
        "",
        "## Authority and maturity",
        "",
        "Active Stage controllers and current source locks override every snapshot here. **PROVISIONAL** entries are discovery aids only; **WORKFLOW** entries are procedures, not selectors. Formal status never removes a card's hypotheses or promotion firewalls.",
        "",
    ]

    sections = [
        ("Formal selectors", lambda e: e["kind"] == "selector"),
        ("Formal reusable weapons", lambda e: e["kind"] == "weapon" and e["maturity"] == "FORMAL"),
        ("Formal workflows", lambda e: e["kind"] == "workflow"),
        ("Provisional active-stage snapshots", lambda e: e["maturity"] == "PROVISIONAL"),
    ]
    for title, predicate in sections:
        lines += [f"## {title}", "", "| ID | Role | Stage | Source |", "|---|---|---|---|"]
        for entry in filter(predicate, entries):
            stage = source_stage(entry)
            role = entry.get("role", "")
            lines.append(f"| `{entry['id']}` | `{role}` | {stage} | {link(entry['path'])} |")
        lines.append("")

    lines += ["## Retired IDs", "", "| Retired ID | Use instead |", "|---|---|"]
    for harvest in data.get("provisional_harvests", []):
        for old, successor in sorted(harvest.get("retired_merged_ids", {}).items()):
            lines.append(f"| `{old}` | `{successor}` |")

    lines += ["", "## Stable source libraries", ""]
    for path in data.get("stable_weapon_libraries", []):
        lines.append(f"- {link(path)}")

    lines += ["", "## Registry support and provenance", "", "| Class | Record | Purpose |", "|---|---|---|"]
    for record in data.get("support_records", []):
        lines.append(f"| **{record['class']}** | {link(record['path'])} | {record['role']} |")

    lines += [
        "",
        "## Historical and deep lookup",
        "",
        "Use [`deep-source-index.md`](deep-source-index.md) for Stage14, Toolbox, StructureRadar, external-search, failure-history, and other deep provenance. Superseded compiled indexes are historical records only:",
        "",
    ]
    for path in data.get("superseded_indexes", []):
        lines.append(f"- {link(path)}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if catalog.md is stale")
    args = parser.parse_args()

    data = json.loads(INDEX.read_text())
    entries, errors = collect(data)
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1

    expected = render(data, entries)
    if args.check:
        if not CATALOG.exists() or CATALOG.read_text() != expected:
            print("ERROR: catalog.md is stale; run sync_arsenal_catalog.py", file=sys.stderr)
            return 1
        print(f"PASS: {len(entries)} active IDs; paths, successors, and catalog verified")
        return 0

    CATALOG.write_text(expected)
    print(f"wrote {CATALOG.relative_to(HERE.parent.parent)} ({len(entries)} active IDs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
