#!/usr/bin/env python3
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent

# Seven audited branch lines on P^2.
lines = {
    "Lx": "x",
    "Ly": "y",
    "Lz": "z",
    "Lxy": "x+y",
    "Lxz": "x+z",
    "Lyz": "y+z",
    "Ls": "x+y+z",
}

# Exact endpoint Kummer/sign-cover square roots.
roots = {
    "Lx": "a1",
    "Ly": "a2",
    "Lz": "a3",
    "Lxy": "b3",
    "Lxz": "b2",
    "Lyz": "b1",
    "Ls": "c",
}

# Choose Ls as the projective line at infinity.  Every affine line factor is
# represented in the function field by Li/Ls, and under the endpoint map each
# such ratio is the square (root_i/c)^2.
infinity = "Ls"
affine = [k for k in lines if k != infinity]
pullback_ratios = {
    k: f"({roots[k]}/{roots[infinity]})^2" for k in affine
}

# Ford's audited line-arrangement Br[2] presentation is generated by degree-two
# symbols in the affine line factors, modulo concurrence/incidence relations.
# Since every affine factor pulls back to a square, every ambient pair-symbol
# already vanishes in the endpoint function field.  Hence any quotient of their
# span, including the certified 9-dimensional Ford group, has zero pullback.
pairs = []
for i, a in enumerate(affine):
    for b in affine[i+1:]:
        pairs.append({
            "symbol": f"({a}/{infinity}, {b}/{infinity})_2",
            "first_pullback": pullback_ratios[a],
            "second_pullback": pullback_ratios[b],
            "pullback_zero_reason": "both entries are squares",
        })

assert len(affine) == 6
assert len(pairs) == 15
assert set(roots) == set(lines)

cert = {
    "schema": "STAGE33_04_FORD_KUMMER_PULLBACK_ZERO_V1",
    "source_locks": {
        "internal_ford_audit": "stages/stage29/29-15/brauer-line9-execution.md",
        "ford_primary": "Timothy J. Ford, Comm. Algebra 45 (2017), Thm. 1.1 and line-arrangement discussion",
        "endpoint_map": "[a1:a2:a3:b1:b2:b3:c] -> [a1^2:a2^2:a3^2]",
    },
    "line_equations": lines,
    "square_root_coordinates": roots,
    "chosen_line_at_infinity": infinity,
    "affine_factor_pullbacks": pullback_ratios,
    "ambient_pair_symbol_count": len(pairs),
    "ambient_pair_symbols": pairs,
    "ford_geometric_br2_dimension": 9,
    "ford_geometric_br2_pullback_rank_to_endpoint_function_field": 0,
    "ford_geometric_br2_pullback_zero": True,
    "reason": "all six affine line factors Li/Ls become squares (root_i/c)^2 on the endpoint Kummer cover, so every Ford 2-symbol generator restricts to zero before concurrence relations are imposed",
    "combinatorial_rank_one_channel_superseded_for_actual_symbol_pullback": True,
    "physical_boundary_intrinsic_residue_cycle_space_still_open": True,
    "br0g_discharged": False,
    "next_exact_leaf": "L33-04-INTRINSIC-QFIXED61-TO-PHYSICAL-UNRAMIFIED-KERNEL",
    "theorem_credit": False,
    "endpoint_credit": False,
    "perfect_cuboid_nonexistence_claim": False,
}
canonical = json.dumps(cert, sort_keys=True, separators=(",", ":")).encode()
cert["canonical_sha256"] = hashlib.sha256(canonical).hexdigest()
(ROOT / "ford-kummer-pullback-zero.json").write_text(
    json.dumps(cert, indent=2, sort_keys=True) + "\n", encoding="utf-8"
)
print(json.dumps({
    "success": True,
    "ford_br2_dim": 9,
    "pullback_rank": 0,
    "all_seven_branch_forms_have_square_roots": True,
    "next_exact_leaf": cert["next_exact_leaf"],
    "certificate_sha256": cert["canonical_sha256"],
}, indent=2, sort_keys=True))
