#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
from math import gcd
from pathlib import Path

# Source lock: Freitag--Salvati Manni, arXiv:1303.6495v1,
# Section 4, Lemma 4.1.  Gamma'[4]/Gamma[8] is V4, acts freely on X(8),
# and its three nontrivial mod-8 representatives are the matrices below.
# Section 2 states g(X(8))=5.  Gamma'[4] is defined by a+b+c == 1 mod 8.
MODULUS = 8
GENUS_X8 = 5
V4_MATRICES = {
    "u": ((1, 4), (4, 1)),
    "v": ((5, 4), (0, 5)),
    "uv": ((5, 0), (4, 5)),
}
# T^4 from Gamma[4]/Gamma[8].  It is outside Gamma'[4] since 1+4+0 == 5 mod 8.
T4 = ((1, 4), (0, 1))


def csha(value: object) -> str:
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


def cusp_canon(pair: tuple[int, int]) -> tuple[int, int]:
    a, c = (pair[0] % MODULUS, pair[1] % MODULUS)
    neg = ((-a) % MODULUS, (-c) % MODULUS)
    return min((a, c), neg)


def all_x8_cusps() -> list[tuple[int, int]]:
    # For Gamma(N), N>2: primitive vectors mod N, modulo simultaneous sign.
    return sorted({
        cusp_canon((a, c))
        for a in range(MODULUS)
        for c in range(MODULUS)
        if gcd(gcd(a, c), MODULUS) == 1
    })


def act(matrix: tuple[tuple[int, int], tuple[int, int]], cusp: tuple[int, int]) -> tuple[int, int]:
    (a, b), (c, d) = matrix
    x, y = cusp
    return cusp_canon((a * x + b * y, c * x + d * y))


def permutation(matrix, cusps: list[tuple[int, int]]) -> tuple[int, ...]:
    index = {x: i for i, x in enumerate(cusps)}
    return tuple(index[act(matrix, x)] for x in cusps)


def compose(p: tuple[int, ...], q: tuple[int, ...]) -> tuple[int, ...]:
    return tuple(p[q[i]] for i in range(len(p)))


def closure(generators: list[tuple[int, ...]], n: int) -> set[tuple[int, ...]]:
    ident = tuple(range(n))
    group = {ident}
    frontier = [ident]
    while frontier:
        g = frontier.pop()
        for h in generators:
            for k in (compose(g, h), compose(h, g)):
                if k not in group:
                    group.add(k)
                    frontier.append(k)
    return group


def orbit(group: set[tuple[int, ...]], i: int) -> tuple[int, ...]:
    return tuple(sorted({g[i] for g in group}))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", type=Path)
    args = ap.parse_args()

    cusps = all_x8_cusps()
    if len(cusps) != 24:
        raise ValueError(f"X(8) cusp count regression: {len(cusps)}")

    pu = permutation(V4_MATRICES["u"], cusps)
    pv = permutation(V4_MATRICES["v"], cusps)
    puv = permutation(V4_MATRICES["uv"], cusps)
    pt = permutation(T4, cusps)
    ident = tuple(range(len(cusps)))

    if compose(pu, pu) != ident or compose(pv, pv) != ident or compose(puv, puv) != ident:
        raise ValueError("V4 generator ceased to have order two on X(8) cusps")
    if compose(pu, pv) != puv or compose(pv, pu) != puv:
        raise ValueError("source-locked three nontrivial classes ceased to form V4")

    v4 = closure([pu, pv], len(cusps))
    if len(v4) != 4:
        raise ValueError(f"V4 action size regression: {len(v4)}")
    if any(g != ident and any(g[i] == i for i in range(len(cusps))) for g in v4):
        raise ValueError("V4 action unexpectedly fixed an X(8) cusp")

    seen: set[int] = set()
    v4_orbits: list[tuple[int, ...]] = []
    for i in range(len(cusps)):
        if i in seen:
            continue
        o = orbit(v4, i)
        if len(o) != 4:
            raise ValueError(f"V4 cusp orbit size regression: {o}")
        v4_orbits.append(o)
        seen.update(o)
    if len(v4_orbits) != 6 or len(seen) != 24:
        raise ValueError("X(8)/V4 cusp orbit partition regression")

    # Gamma[4]/Gamma[8] is generated by Gamma'[4]/Gamma[8] and T^4.
    full_g4 = closure([pu, pv, pt], len(cusps))
    if len(full_g4) != 8:
        raise ValueError(f"Gamma[4]/Gamma[8] cusp action size regression: {len(full_g4)}")
    if any(compose(g, h) != compose(h, g) for g in full_g4 for h in full_g4):
        raise ValueError("Gamma[4]/Gamma[8] action ceased to be elementary abelian")
    if pt in v4:
        raise ValueError("T^4 unexpectedly entered Gamma'[4]/Gamma[8]")

    # T^4 normalizes V4 and induces the nontrivial involution on C0=X(8)/V4.
    # Every one of the six quotient cusps is fixed setwise.
    orbit_index = {i: j for j, o in enumerate(v4_orbits) for i in o}
    induced = tuple(orbit_index[pt[o[0]]] for o in v4_orbits)
    if induced != tuple(range(6)):
        raise ValueError(f"T^4 did not fix all six V4 cusp orbits: {induced}")

    # Since X(8)->C0 is free degree four, Riemann--Hurwitz gives g(C0)=2.
    numerator = 2 * GENUS_X8 - 2
    if numerator % 4:
        raise ValueError("free V4 quotient genus arithmetic regression")
    genus_c0 = (numerator // 4 + 2) // 2
    if 2 * genus_c0 - 2 != numerator // 4 or genus_c0 != 2:
        raise ValueError(f"C0 genus regression: {genus_c0}")

    # The induced involution already has >=6 fixed points (the six quotient cusps).
    # R-H for C0 -> C0/<T4> says
    #   2g(C0)-2 = 2(2gQ-2)+r.
    # With g(C0)=2 and r>=6, nonnegative gQ forces r=6 and gQ=0.
    quotient_genus = 0
    total_fixed_points = 6
    if 2 * genus_c0 - 2 != 2 * (2 * quotient_genus - 2) + total_fixed_points:
        raise ValueError("degree-two quotient Riemann--Hurwitz regression")

    orbit_rows = []
    for j, o in enumerate(v4_orbits, start=1):
        pts = [cusps[i] for i in o]
        t_pairs = []
        paired = set()
        for i in o:
            if i in paired:
                continue
            k = pt[i]
            t_pairs.append([list(cusps[i]), list(cusps[k])])
            paired.add(i)
            paired.add(k)
        orbit_rows.append({
            "quotient_cusp_id": j,
            "x8_cusps_mod8_pm": [list(x) for x in pts],
            "T4_pairs_inside_orbit": t_pairs,
            "T4_fixed_as_quotient_cusp": True,
        })

    result = {
        "schema": "STAGE32_POST1473_X8_V4_CUSP_QUOTIENT_REPLAY_V1",
        "stage": 32,
        "status": "PASS",
        "source_lock": {
            "paper": "Freitag--Salvati Manni, Parametrization of the box variety by theta functions",
            "arxiv": "1303.6495v1",
            "section": "4, Lemma 4.1; Section 2 genus statement",
            "Gamma_prime_4_condition": "a+b+c == 1 mod 8",
            "V4_mod8_representatives": {k: [list(r) for r in m] for k, m in V4_MATRICES.items()},
            "outside_coset_representative_T4": [list(r) for r in T4],
            "genus_X8": GENUS_X8,
        },
        "exact_group_checks": {
            "x8_cusp_count": 24,
            "V4_order": len(v4),
            "V4_free_on_24_cusps": True,
            "Gamma4_over_Gamma8_order": len(full_g4),
            "T4_outside_V4": True,
            "V4_quotient_cusp_count": len(v4_orbits),
            "T4_fixes_all_six_V4_cusp_orbits": True,
        },
        "quotient_geometry": {
            "C0_definition": "X(8)/(Gamma'[4]/Gamma[8])",
            "X8_to_C0_degree": 4,
            "X8_to_C0_etale": True,
            "genus_C0": genus_c0,
            "C0_to_X4_degree": 2,
            "C0_to_X4_fixed_points": total_fixed_points,
            "C0_to_X4_fixed_points_are_exactly_the_six_quotient_cusps": True,
            "genus_X4": quotient_genus,
            "six_quotient_cusps_are_hyperelliptic_Weierstrass_points_of_C0": True,
        },
        "quotient_cusp_orbits": orbit_rows,
        "firewall": "abstract modular cusp quotient only; no retained boundary-label-to-cusp-orbit identification, no O188 A/B/C exclusion, and no receiver/theorem/endpoint credit",
    }
    result["canonical_sha256_without_this_field"] = csha(result)
    text = json.dumps(result, sort_keys=True, separators=(",", ":"))
    print(text)
    if args.output:
        args.output.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")


if __name__ == "__main__":
    main()
