#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import math
from pathlib import Path

import sympy
from sympy import Matrix, ZZ
from sympy.matrices.normalforms import hermite_normal_form
from sympy.polys.matrices import DomainMatrix
from sympy.polys.matrices.normalforms import smith_normal_decomp

from direct_picard_slice_bridge import DirectPicardSliceBridge
from direct_picard_slice_quadratic_bound import DirectPicardSliceQuadraticBound, rational_matrix_payload


def csha(value: object) -> str:
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()


def load_retained(path: Path, module_name: str) -> dict:
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise ValueError(f"cannot load retained module: {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.load()


def integer_matrix_payload(m: Matrix) -> list[list[int]]:
    return [[int(m[i, j]) for j in range(m.cols)] for i in range(m.rows)]


def generator_order_from_dual_coordinates(column: Matrix) -> int:
    order = 1
    for value in column:
        order = math.lcm(order, int(sympy.denom(value)))
    return order


def build_diagnostic(marking: dict, bundle: dict) -> dict:
    bridge = DirectPicardSliceBridge.from_retained(marking, bundle)
    bound = DirectPicardSliceQuadraticBound.from_retained(marking, bundle)
    gram = Matrix(bundle["picard_gram_64x64"])
    phi = Matrix([
        list(bridge.degree_functional),
        list(bridge.exceptional_mass_functional),
        list(bridge.first_normal_half_functional),
    ])
    if phi.shape != (3, 64) or int(phi.rank()) != 3:
        raise ValueError("direct Picard slice functional regression")

    # Exact Smith coordinates make the last 61 coordinates a saturated
    # integral basis for ker(phi).  If D=S*phi*T and z=T^{-1}x, then
    # D*z=S*t.  The first three z coordinates are fixed by t and the last
    # 61 range freely over the integral slice kernel.
    phi_dm = DomainMatrix.from_Matrix(phi).convert_to(ZZ)
    D_dm, S_dm, T_dm = smith_normal_decomp(phi_dm)
    if S_dm * phi_dm * T_dm != D_dm:
        raise ValueError("Smith decomposition reconstruction regression")
    D = D_dm.to_Matrix()
    S = S_dm.to_Matrix()
    T = T_dm.to_Matrix()
    diagonal = [int(D[i, i]) for i in range(3)]
    if any(v == 0 for v in diagonal):
        raise ValueError(f"rank-three Smith diagonal regression: {diagonal}")
    image_index = math.prod(abs(v) for v in diagonal)
    expected_index = int(bridge.certificate["target_image"]["image_index"])
    if image_index != expected_index:
        raise ValueError(f"Smith/HNF image-index mismatch: {image_index} != {expected_index}")

    t_det = int(T.det())
    s_det = int(S.det())
    if abs(t_det) != 1 or abs(s_det) != 1:
        raise ValueError(f"Smith transforms not unimodular: detS={s_det}, detT={t_det}")

    kernel_basis = T[:, 3:]
    if kernel_basis.shape != (64, 61) or phi * kernel_basis != Matrix.zeros(3, 61):
        raise ValueError("saturated slice-kernel basis regression")

    transformed_gram = T.T * gram * T
    A = transformed_gram[:3, :3]
    C = transformed_gram[:3, 3:]
    H = transformed_gram[3:, 3:]
    B = -H
    if B.shape != (61, 61) or B != B.T:
        raise ValueError("slice-kernel Gram regression")

    # Exact positive-definite certificate for -G|ker(phi).
    L, P = B.LDLdecomposition(hermitian=False)
    if L * P * L.T != B:
        raise ValueError("slice-kernel LDL reconstruction regression")
    pivots = [P[i, i] for i in range(P.rows)]
    if any(v <= 0 for v in pivots):
        raise ValueError("slice-kernel positive Gram has nonpositive LDL pivot")

    det_b = abs(int(B.det()))
    if det_b == 0:
        raise ValueError("slice-kernel discriminant vanished")

    # For fixed Smith target coordinate u, the integer kernel coordinate v has
    # q(u,v)=u^T A u + 2u^T C v - v^T B v.  The real maximizer is
    # v*=B^{-1} C^T u.  Hence the integrality loss is the closest-vector cost
    # of the class C^T u mod B Z^61.  Only the subgroup generated by the three
    # columns of C^T can ever occur, no matter how many (d,e,a) slices exist.
    shift_generators = C.T
    B_inv_shift = B.inv() * shift_generators
    schur = A + C * B_inv_shift

    diag3 = Matrix.diag(*diagonal)
    target_from_u = S.inv() * diag3
    existing_dual = Matrix(bound.dual_integer_matrix) / int(bound.dual_denominator)
    schur_from_existing = target_from_u.T * existing_dual * target_from_u
    if schur != schur_from_existing:
        raise ValueError("Smith-coordinate continuous bound does not match existing direct quadratic certificate")

    generator_orders = [generator_order_from_dual_coordinates(B_inv_shift[:, j]) for j in range(3)]

    enlarged_lattice = B.row_join(shift_generators)
    enlarged_hnf = hermite_normal_form(enlarged_lattice)
    if enlarged_hnf.shape != (61, 61):
        raise ValueError(f"generated superlattice HNF shape regression: {enlarged_hnf.shape}")
    enlarged_index = abs(int(enlarged_hnf.det()))
    if enlarged_index == 0 or det_b % enlarged_index != 0:
        raise ValueError("generated subgroup index does not divide slice-kernel discriminant")
    relevant_subgroup_order = det_b // enlarged_index
    if any(relevant_subgroup_order % order != 0 for order in generator_orders):
        raise ValueError("generator order does not divide generated subgroup order")

    cert = {
        "schema": "STAGE32_RESIDUAL32_01_DIRECT_PICARD_INTEGRAL_COSET_DIAGNOSTIC_V1",
        "mode": "EXACT_FINITE_DISCRIMINANT_SUBGROUP_FOR_D_E_A_SLICE_INTEGRALITY_LOSS",
        "bridge_certificate_sha256": bridge.certificate["canonical_sha256_without_this_field"],
        "quadratic_certificate_sha256": bound.certificate["canonical_sha256_without_this_field"],
        "picard_rank": 64,
        "slice_rank": 3,
        "slice_kernel_rank": 61,
        "smith": {
            "diagonal": diagonal,
            "image_index": image_index,
            "S_determinant": s_det,
            "T_determinant": t_det,
            "reconstruction_exact": True,
            "kernel_basis_saturated_by_unimodular_coordinates": True,
        },
        "slice_kernel": {
            "positive_gram_rank": 61,
            "positive_definite_exact": True,
            "ldl_positive_pivot_count": len(pivots),
            "ldl_diagonal_sha256": csha([str(v) for v in pivots]),
            "discriminant_order": det_b,
        },
        "integral_shift_subgroup": {
            "generator_count": 3,
            "generator_orders": generator_orders,
            "ambient_discriminant_order": det_b,
            "superlattice_index_in_Z61": enlarged_index,
            "relevant_subgroup_order": relevant_subgroup_order,
            "all_integrality_loss_classes_lie_in_this_subgroup": True,
            "class_formula": "[C^T*u] in Z^61 / B*Z^61",
        },
        "continuous_bound_crosscheck": {
            "exact": True,
            "smith_schur_payload": rational_matrix_payload(schur),
            "matches_existing_direct_quadratic_bound": True,
        },
        "interpretation": {
            "full_discriminant_group_enumeration_required": False,
            "candidate_slice_count_used_to_define_class_table": False,
            "next_exact_leaf_if_subgroup_manageable": "compute closest-vector penalty once per reachable subgroup class and apply corrected bound to FULL178 direct slices",
            "next_exact_leaf_if_subgroup_large": "analyze the rank-at-most-three generated subgroup and its target-period quotient before any slice enumeration",
        },
        "numerical_closevectors_complete": False,
        "numerical_row_complete": False,
        "theorem_credit": False,
        "receiver_credit": False,
        "route_credit": False,
        "perfect_cuboid_existence_claim": False,
        "perfect_cuboid_nonexistence_claim": False,
    }
    cert["canonical_sha256_without_this_field"] = csha(cert)
    return cert


def main() -> None:
    parser = argparse.ArgumentParser(description="Diagnose the finite integral coset correction for Stage32 direct Picard slices.")
    parser.add_argument("--retained", required=True, type=Path)
    parser.add_argument("--marking", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    bundle = load_retained(args.retained, "stage32_integral_coset_picard")
    marking = load_retained(args.marking, "stage32_integral_coset_marking")
    cert = build_diagnostic(marking, bundle)
    args.output.write_text(json.dumps(cert, indent=2, sort_keys=True) + "\n")
    print(json.dumps({
        "verdict": "PASS_DIRECT_PICARD_INTEGRAL_COSET_DIAGNOSTIC",
        "smith_diagonal": cert["smith"]["diagonal"],
        "slice_kernel_discriminant_order": cert["slice_kernel"]["discriminant_order"],
        "generator_orders": cert["integral_shift_subgroup"]["generator_orders"],
        "relevant_subgroup_order": cert["integral_shift_subgroup"]["relevant_subgroup_order"],
        "canonical_sha256": cert["canonical_sha256_without_this_field"],
    }, sort_keys=True))


if __name__ == "__main__":
    main()
