#!/usr/bin/env python3
"""Profile the exact residual after Stage33-11 global naturality nonclosure.

Execute the intrinsic-A2 naturality certifier once, retain its exact action
matrices even when its intentional nonclosure exit fires, then compute:
  * bases of Hom_H(A,K) and Hom_H(A,H1(V4,K));
  * the universal source kernel annihilated by every map in each Hom space;
  * the common universal kernel relevant to the absolute two-factor argument;
  * cyclic source submodules generated by each of the 26 named source basis
    directions under the seven signs plus two actual coordinate swaps.

This is a 33-11b block/orbit scout. It does not invent connecting columns.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
VERIFIER = HERE / "certify_stage33_11_intrinsic_at2_naturality.py"
OUT = HERE / "stage33-11-equivariant-forced-zero-blocks.json"
QDIM, KDIM, H1DIM = 26, 14, 16


def csha(obj):
    return hashlib.sha256(json.dumps(obj, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


# exec rather than runpy so the exact residual action matrices remain available
# after the certifier intentionally exits on a mathematically valid nonclosure.
ns = {"__name__": "__main__", "__file__": str(VERIFIER)}
try:
    exec(compile(VERIFIER.read_text(encoding="utf-8"), str(VERIFIER), "exec"), ns)
except SystemExit as exc:
    if "does not close both absolute factors" not in str(exc):
        raise

source_actions = ns["source_actions"]
K_actions = ns["K_actions"]
H1_actions = ns["H1_actions"]
sign = ns["sign"]
nullspace2 = sign["nullspace2"]
row_basis = sign["row_basis"]
rowmul2 = sign["rowmul2"]
rank2 = sign["rank2"]

if ns["hom_A_K_dim"] != 24 or ns["hom_A_H1_dim"] != 33:
    raise SystemExit(
        f"33-11a residual moved: K={ns['hom_A_K_dim']} H1={ns['hom_A_H1_dim']}"
    )


def hom_equations(source, target, sdim, tdim):
    equations = []
    for S, T in zip(source, target):
        for i in range(sdim):
            for j in range(tdim):
                row = [0] * (sdim * tdim)
                for k in range(sdim):
                    if int(S[i][k]) & 1:
                        row[k * tdim + j] ^= 1
                for ell in range(tdim):
                    if int(T[ell][j]) & 1:
                        row[i * tdim + ell] ^= 1
                if any(row):
                    equations.append(row)
    return equations


def universal_kernel(hom_basis, sdim, tdim):
    # v is universally killed iff v*D=0 for every equivariant D and every
    # target coordinate. These are linear equations in the source vector v.
    equations = []
    for flat in hom_basis:
        for j in range(tdim):
            row = [int(flat[i * tdim + j]) & 1 for i in range(sdim)]
            if any(row):
                equations.append(row)
    basis = nullspace2(equations, sdim)
    return basis, equations


K_eq = hom_equations(source_actions, K_actions, QDIM, KDIM)
H1_eq = hom_equations(source_actions, H1_actions, QDIM, H1DIM)
K_hom_basis = nullspace2(K_eq, QDIM * KDIM)
H1_hom_basis = nullspace2(H1_eq, QDIM * H1DIM)
if len(K_hom_basis) != 24 or len(H1_hom_basis) != 33:
    raise SystemExit("Hom basis dimension disagrees with Stage33-11a")

K_uker, K_uker_eq = universal_kernel(K_hom_basis, QDIM, KDIM)
H1_uker, H1_uker_eq = universal_kernel(H1_hom_basis, QDIM, H1DIM)
common_eq = K_uker_eq + H1_uker_eq
common_uker = nullspace2(common_eq, QDIM)


def named_basis_forced_zero(equations):
    out = []
    for i in range(QDIM):
        if all((int(row[i]) & 1) == 0 for row in equations):
            out.append(i + 1)
    return out


forced_K = named_basis_forced_zero(K_uker_eq)
forced_H1 = named_basis_forced_zero(H1_uker_eq)
forced_common = named_basis_forced_zero(common_eq)

# Cyclic H-submodule generated by each named source basis direction.
def canonical_cyclic_submodule(index):
    e = [0] * QDIM; e[index] = 1
    basis, _ = row_basis([e], QDIM)
    while True:
        candidates = list(basis)
        for v in basis:
            candidates.extend(rowmul2(v, A) for A in source_actions)
        new_basis, _ = row_basis(candidates, QDIM)
        if len(new_basis) == len(basis):
            basis = new_basis
            break
        basis = new_basis
    return tuple(tuple(int(x) & 1 for x in row) for row in basis)


classes = {}
for i in range(QDIM):
    key = canonical_cyclic_submodule(i)
    classes.setdefault(key, []).append(i + 1)
cyclic = [
    {"dimension_f2": len(key), "named_source_directions_1based": members}
    for key, members in classes.items()
]
cyclic.sort(key=lambda r: (r["dimension_f2"], r["named_source_directions_1based"]))

cert = {
    "schema": "STAGE33_11_EQUIVARIANT_FORCED_ZERO_BLOCK_PROFILE_V1",
    "stage": "33-11",
    "branch": "33-11b_SYMMETRY_BLOCK_CLOSURE",
    "source_locks": {
        "stage33_11a_intrinsic_naturality_certificate_sha256": ns["cert"]["canonical_sha256"],
        "actual_galois_at2_certificate_sha256": ns["intrinsic_cert"]["canonical_sha256"],
    },
    "inherited_exact_nonclosure": {
        "Hom_H_A_to_K_dimension_f2": len(K_hom_basis),
        "Hom_H_A_to_finite_H1_dimension_f2": len(H1_hom_basis),
        "global_naturality_alone_closes_stage33_11": False,
    },
    "universal_source_kernels": {
        "kernel_annihilated_by_every_Hom_A_to_K_dimension_f2": len(K_uker),
        "kernel_annihilated_by_every_Hom_A_to_finite_H1_dimension_f2": len(H1_uker),
        "common_kernel_annihilated_by_every_map_to_both_factors_dimension_f2": len(common_uker),
        "named_basis_directions_forced_zero_for_K_1based": forced_K,
        "named_basis_directions_forced_zero_for_finite_H1_1based": forced_H1,
        "named_basis_directions_forced_zero_for_both_1based": forced_common,
    },
    "cyclic_source_submodules": {
        "distinct_named_cyclic_submodules": len(cyclic),
        "records": cyclic,
    },
    "exact_consequence": {
        "connecting_columns_materialized": 0,
        "named_connecting_directions_forced_zero_by_current_symmetry": len(forced_common),
        "all_26_directions_covered": len(forced_common) == QDIM,
        "stage33_11_closed_exact": False,
        "next_branch": "33-11c_INDIVIDUAL_OR_SMALLEST_BLOCK_FALLBACK" if len(forced_common) < QDIM else "NONE",
        "remote_cas_used": False,
        "smith_form_used": False,
    },
}
cert["canonical_sha256"] = csha(cert)
OUT.write_text(json.dumps(cert, indent=2, sort_keys=True) + "\n", encoding="utf-8")
print(json.dumps({
    "success": True,
    "Hom_A_K_dim": len(K_hom_basis),
    "Hom_A_H1_dim": len(H1_hom_basis),
    "universal_kernel_K_dim": len(K_uker),
    "universal_kernel_H1_dim": len(H1_uker),
    "universal_kernel_common_dim": len(common_uker),
    "named_directions_forced_zero": forced_common,
    "distinct_cyclic_submodules": len(cyclic),
    "certificate_sha256": cert["canonical_sha256"],
}, indent=2, sort_keys=True))
