#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[6]
NODE = ROOT / "stages/stage32/final-chain/32-03-multibranch/nodes/MB104"

LOCKS = {
    "stages/stage32/final-chain/32-03-multibranch/nodes/MB104/A1-CONTRACTION-CONDUCTOR.json": "fda08685a63caab19851d0d6e5bac353092c888e",
    "docs/arsenal/cards/provisional/S32-PW09.md": "14755f8d7a14dac75a80eb711b6083c5f3b0ea3b",
}


def git_blob_sha(path: Path) -> str:
    data = path.read_bytes()
    return hashlib.sha1(b"blob " + str(len(data)).encode() + b"\0" + data).hexdigest()


def main() -> None:
    for rel, expected in LOCKS.items():
        got = git_blob_sha(ROOT / rel)
        assert got == expected, (rel, got, expected)

    wall = json.loads((NODE / "SPECIAL-DISCRIMINANT-CAPACITY-WALL.json").read_text())
    a1 = json.loads((NODE / "A1-CONTRACTION-CONDUCTOR.json").read_text())
    pw09 = (ROOT / "docs/arsenal/cards/provisional/S32-PW09.md").read_text()

    assert wall["schema"] == "STAGE32_MB104_SPECIAL_DISCRIMINANT_CAPACITY_WALL_V1"
    assert "Disc(pi)=Br+2A" in pw09
    assert a1["s32_pw09_interface"]["formula"] == "Disc(pi)=Br(f)+2*A"

    # For A=k[[t]], B'=A+uA with u^2=t and B_N=A+t^N*uA:
    # B'/B_N is generated by u modulo t^N*u, hence has A-length N.
    # In basis [1,t^N*u], the quadratic trace matrix is
    # diag(2,2*t^(2N+1)); its determinant has t-valuation 2N+1.
    # The normalization B' has discriminant valuation 1, so the correction
    # is exactly 2N, matching Disc=Br+2A.
    for N in range(0, 10001):
        index_length = N
        normalized_disc_valuation = 1
        order_disc_valuation = 2 * N + 1
        assert order_disc_valuation == normalized_disc_valuation + 2 * index_length

    local = wall["local_order_family"]
    assert local["normalized_projection_degree"] == 2
    assert local["normalized_branch_discriminant_valuation"] == 1
    assert local["finite_free_rank_over_A"] == 2
    assert local["integral_domain"] is True
    assert local["normalization"] == "B'"
    assert local["matches_even_correction_formula"] is True

    cap = wall["capacity_consequence"]
    assert cap["projection_degree_fixed"] == 2
    assert cap["special_base_values_needed"] == 1
    assert cap["normalization_index_unbounded"] is True
    assert cap["discriminant_multiplicity_unbounded"] is True
    assert cap["no_upper_bound_from_projection_degree_and_special_value_count_alone"] is True

    fw = wall["firewalls"]
    assert fw["local_order_family_embeds_in_box_surface_claimed"] is False
    assert fw["local_order_family_is_a1_contraction_model_claimed"] is False
    assert fw["generic_nonclosure_refutes_ambient_geometry_bound"] is False
    assert fw["finite_degree_window_proved"] is False
    assert fw["receiver_credit"] is False
    assert fw["merge_authorized"] is False

    print("MB104 special-discriminant capacity-wall verifier PASS")
    print("fixed normalized degree=2; one special value; index N unbounded")
    print("disc valuation=2N+1=1+2N for N=0..10000")
    print("generic projection-degree/special-value capacity route is nonclosing")


if __name__ == "__main__":
    main()
