#!/usr/bin/env python3
import hashlib
import json
import runpy
from pathlib import Path

HERE = Path(__file__).resolve().parent
PASS = "PASS STAGE32_MB104_000707_E2_CONDUCTOR_DETERMINANT_REDUCTION_V1"
ACTIVE = "MB104-GENUS1-SPAN5-BALANCED16-000707-E2-RESIDUAL-LIFT-CONDUCTOR-PAIR-MAP"

LOCKS = {
    "HUMAN_NOTE": (
        "stages/stage32/final-chain/32-03-multibranch/nodes/MB104/GENUS1-SPAN5-BALANCED16-000707-E2-CONDUCTOR-DETERMINANT-REDUCTION.md",
        "b545ae9675570c86a9d1a9803e5272350a0e77e0",
    ),
    "EXTERNAL_PRODUCT_CERT": (
        "stages/stage32/final-chain/32-03-multibranch/nodes/MB104/GENUS1-SPAN5-BALANCED16-000707-E2-EXTERNAL-PRODUCT-PICARD-REDUCTION-CERTIFICATE.json",
        "8ee4c7a3b3f445c9f34cb7b37f55a22fd7e99a06",
    ),
    "G_FIXED_CERT": (
        "stages/stage32/final-chain/32-03-multibranch/nodes/MB104/GENUS1-SPAN5-BALANCED16-000707-E2-G-FIXED-JACOBIAN-TORSION-CERTIFICATE.json",
        "3225551e7f22878f4a481f0a5e5d601e36bed781",
    ),
    "G_FIXED_VERIFIER": (
        "stages/stage32/final-chain/32-03-multibranch/nodes/MB104/verify_mb104_balanced16_000707_e2_g_fixed_jacobian_torsion.py",
        "07e54f9f5eb5c01f17dcdd099aada75ef6e95716",
    ),
    "PRODUCT_CERT": (
        "stages/stage32/final-chain/32-03-multibranch/nodes/MB104/GENUS1-SPAN5-BALANCED16-000707-E2-PRODUCT-CORRESPONDENCE-LINEARIZATION-CERTIFICATE.json",
        "ea8bd879093a5ec2054f560807fa05806f96a553",
    ),
}


def req(cond, msg):
    if not cond:
        raise SystemExit("FAIL: " + msg)


def repo_root():
    p = HERE
    while p != p.parent:
        if (p / "AGENTS.md").is_file() and (p / "stages").is_dir():
            return p
        p = p.parent
    raise SystemExit("FAIL: repo root")


def blob_sha1(path):
    data = path.read_bytes()
    return hashlib.sha1(f"blob {len(data)}\0".encode() + data).hexdigest()


root = repo_root()
for name, (rel, expected) in LOCKS.items():
    p = root / rel
    req(p.is_file(), f"missing lock {name}: {rel}")
    got = blob_sha1(p)
    req(got == expected, f"SOURCE_LOCK_FAIL {name}: {got} != {expected}")

note = (root / LOCKS["HUMAN_NOTE"][0]).read_text(encoding="utf-8")
ext_cert = json.loads((root / LOCKS["EXTERNAL_PRODUCT_CERT"][0]).read_text(encoding="utf-8"))
g_cert = json.loads((root / LOCKS["G_FIXED_CERT"][0]).read_text(encoding="utf-8"))
prod_cert = json.loads((root / LOCKS["PRODUCT_CERT"][0]).read_text(encoding="utf-8"))

req(ext_cert.get("active_leaf") == ACTIVE, "external-product active leaf")
req(ext_cert.get("scope", {}).get("case") == "e=2", "external-product e2 scope")
req(ext_cert.get("deduction", {}).get("factor_degree_each") == "28*l", "factor degree 28l")
req(g_cert.get("fixed_torus", {}).get("J_C8_G_fixed_structure") == "(Z/2)^5", "full-G fixed group")
req(prod_cert.get("intersection_and_genus", {}).get("normalization_defect_Zbar") == "784*l^2+112*l", "product defect")

for token in [
    "det(pi_1* O_Zbar) ~= A^(-(n+4))",
    "O_C(F_1)",
    "~= A^(n+4) tensor epsilon_1",
    "epsilon_i^2 ~= O_C",
    "J(C8)^H ~= (Z/2)^6",
    "|J(C8)^H|=64",
    "No e=2 closure is claimed",
]:
    req(token in note, f"semantic token missing: {token}")

# Exact arithmetic replay for n=28l and genus five.
for l in range(1, 17):
    n = 28 * l
    delta = 784*l*l + 112*l
    req(n * (n + 4) == delta, f"delta=n(n+4), l={l}")
    req(n + 4 == 4 * (7*l + 1), f"n+4 divisible by four, l={l}")
    req(n * (2*n + 8) == 2 * delta, f"discriminant degree saturation, l={l}")

# Replay exact integral H1 module from the source-locked parent verifier.
ns = runpy.run_path(str(root / LOCKS["G_FIXED_VERIFIER"][0]), run_name="stage32_mb104_gfixed_parent")
q = ns["q"]
eye = ns["eye"]
msub = ns["msub"]
transpose = ns["transpose"]
unit_diagonalize = ns["unit_diagonalize"]

# Active H is generated by the two used singular involutions. In the parent
# standard singular basis these are e1,e2; basis changes inside G preserve SNF.
H_basis = [(1,0,0), (0,1,0)]
bmat = []
for h in H_basis:
    bmat.extend(transpose(msub(q[h], eye(10))))
req(len(bmat) == 20 and len(bmat[0]) == 10, "H fixed matrix shape")

bred, _, _, units = unit_diagonalize(bmat)
req(units == 4, "four unit H-fixed Smith factors")
req(all(bred[i][j] == (1 if i == j else 0) for i in range(4) for j in range(10)), "H fixed I4 block")
req(all(bred[i][j] == 0 for i in range(4,20) for j in range(4)), "H fixed lower-left zero")
req(all(bred[i][j] % 2 == 0 for i in range(4,20) for j in range(4,10)), "H fixed residual even")

half = [[bred[i][j] // 2 for j in range(4,10)] for i in range(4,20)]
hred, _, _, units2 = unit_diagonalize(half)
req(units2 == 6, "six residual half-unit factors")
req(all(hred[i][j] == (1 if i == j else 0) for i in range(6) for j in range(6)), "H fixed half I6")
req(all(hred[i][j] == 0 for i in range(6,16) for j in range(6)), "H fixed half residual zero")
req(2**6 == 64, "H-fixed determinant ambiguity size")

# The 32 full-G twists are 2-torsion and n+4 is even, so they disappear from
# A^(n+4); this is a group-exponent replay independent of a chosen basis.
req((28 + 4) % 2 == 0, "n+4 parity template")
req(ext_cert.get("deduction", {}).get("crude_ordered_pair_ambient_bound") == "4^20", "predecessor finite-Picard context")

for forbidden in [
    "e2_closed: true",
    "receiver_credit: true",
    "theorem_credit: true",
    "endpoint_credit: true",
    "perfect_cuboid_nonexistence_claim: true",
]:
    req(forbidden not in note, f"forbidden credit token: {forbidden}")

print(PASS)
