#!/usr/bin/env python3
import hashlib
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CERT = HERE / "GENUS1-SPAN5-BALANCED16-ZERO-QUARTIC-PIC0-CERTIFICATE.json"
SUB = HERE / "verify_mb104_balanced16_zero_quartic_pic0.py"
SUB_BLOB = "02ff4cf4d7a43de2fe278f4f8950776e7814d042"
SUB_PASS = "PASS STAGE32_MB104_BALANCED16_ZERO_QUARTIC_PIC0_V1"


def require(cond, msg):
    if not cond:
        raise SystemExit(f"FAIL: {msg}")


def blob_sha1(path):
    data = path.read_bytes()
    return hashlib.sha1(f"blob {len(data)}\0".encode() + data).hexdigest()


def mul_poly(a, b):
    out = [0] * (len(a) + len(b) - 1)
    for i, x in enumerate(a):
        for j, y in enumerate(b):
            out[i + j] += x * y
    return tuple(out)


def mod_u2(poly):
    return tuple(poly[:2])


def check_local_length_four():
    # Hyperflex elimination in y=1, W=i*w, z+W=2:
    # (2-z)^2-(2-z^2)=2(z-1)^2.
    sq_2_minus_z = mul_poly((2, -1), (2, -1))
    lhs = tuple(sq_2_minus_z[i] - (2, 0, -1)[i] for i in range(3))
    rhs = tuple(2 * c for c in mul_poly((-1, 1), (-1, 1)))
    require(lhs == rhs == (2, -4, 2), "hyperflex elimination polynomial")

    # Put u=z-1. Then u^2=0 and x^2=2u+u^2.
    # Modulo u^2 this is x^2=2u, so x^4 maps to (2u)^2=4u^2=0.
    x2_as_u = (0, 2, 1)
    reduced_x2 = mod_u2(x2_as_u)
    require(reduced_x2 == (0, 2), "x^2=2u modulo u^2")
    x4_as_u = mul_poly(reduced_x2, reduced_x2)
    require(x4_as_u == (0, 0, 4), "x^4=4u^2 before quotient")
    require(mod_u2(x4_as_u) == (0, 0), "x^4=0 modulo u^2")

    # Conversely u=x^2/2 in the quotient, so the local algebra is generated by x
    # with x^4=0. Together with the degree-four plane-section bound from the
    # source-locked smooth quartic geometry, this gives exact length four at P.


def main():
    cert = json.loads(CERT.read_text())
    require(cert["schema"] == "STAGE32_MB104_BALANCED16_ZERO_QUARTIC_PIC0_V1", "certificate schema")
    require(SUB.is_file(), "subverifier missing")
    got = blob_sha1(SUB)
    if got != SUB_BLOB:
        raise SystemExit(f"SOURCE_LOCK_FAIL: subverifier expected {SUB_BLOB}, got {got}")

    run = subprocess.run(
        [sys.executable, str(SUB)],
        cwd=str(HERE),
        text=True,
        capture_output=True,
    )
    if run.returncode != 0:
        sys.stderr.write(run.stdout)
        sys.stderr.write(run.stderr)
        raise SystemExit("FAIL: source-locked subverifier failed")
    require(SUB_PASS in run.stdout, "subverifier PASS token")

    check_local_length_four()

    geo = cert["geometry"]
    require(geo["representative_plane_section"] == "4P", "certificate plane-section multiplicity")
    require(geo["every_box_node_hyperflex"] is True, "certificate hyperflex transport")
    rc = cert["retained_consequence"]
    require(rc["restriction_bundle_trivial_for_all_l"] is True, "certificate restriction triviality")
    require(rc["restriction_map_nonzero_proved"] is False, "restriction-map firewall")

    print("PASS STAGE32_MB104_BALANCED16_ZERO_QUARTIC_PIC0_V2")
    print(f"source_locked_subverifier={SUB_BLOB}")
    print("local_hyperflex_algebra=u2=0,x2=2u=>x4=0 plane_section_length=4")
    print("restriction_bundle=trivial_all_zero_quartics_all_l restriction_map_still_open")


if __name__ == "__main__":
    main()
