#!/usr/bin/env python3
"""Put the #1419 9-dimensional quotient-to-raw Bockstein extension in normal form.

Input: the compact certificate proving 17 raw-order2 and 9 exact raw-order4
first-residue directions, with nine independent U44 doubles.

Because the 26 quotient A[2] sources form a basis modulo U44, and the nine
nonzero doubles are independent in U44, the subgroup generated by U44 and the
26 chosen raw lifts has exact invariant factors

    (Z/4)^9 direct_sum (Z/2)^52.

This leaf constructs an explicit U44 basis whose first nine vectors are the
nine Bockstein images, so each order-four source q_i satisfies 2 q_i = u'_i.
It also records the already-certified complex-conjugation identity
cc(q_i)-q_i = u'_i, hence cc acts by inversion on each of the nine Z/4 factors.

No global Gersten lift or arithmetic localization cocycle is claimed.
"""

import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "order2-quotient-raw-order4-bockstein-compact.json"
OUT = HERE / "order2-raw-extension-normal-form.json"
EXPECTED_SRC_SHA256 = "30f2a4653619419a42d5513be26c8acf7505e042e4cbef279abd3476c34d1cfa"


def canonical_sha256(obj):
    return hashlib.sha256(
        json.dumps(obj, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()


def rref2(rows, ncols):
    a = [[int(x) & 1 for x in row] for row in rows]
    pivots = []
    r = 0
    for c in range(ncols):
        p = next((i for i in range(r, len(a)) if a[i][c]), None)
        if p is None:
            continue
        a[r], a[p] = a[p], a[r]
        for i in range(len(a)):
            if i != r and a[i][c]:
                a[i] = [x ^ y for x, y in zip(a[i], a[r])]
        pivots.append(c)
        r += 1
        if r == len(a):
            break
    return a, pivots


def rank2(rows, ncols):
    return len(rref2(rows, ncols)[1])


def inv2(matrix):
    n = len(matrix)
    a = [
        [int(x) & 1 for x in matrix[i]] + [int(i == j) for j in range(n)]
        for i in range(n)
    ]
    for c in range(n):
        p = next((i for i in range(c, n) if a[i][c]), None)
        if p is None:
            raise SystemExit("basis-change matrix is singular")
        a[c], a[p] = a[p], a[c]
        for i in range(n):
            if i != c and a[i][c]:
                a[i] = [x ^ y for x, y in zip(a[i], a[c])]
    return [row[n:] for row in a]


def bits_from_hex_le(value, nbits):
    z = int(value, 16)
    return [(z >> i) & 1 for i in range(nbits)]


src = json.loads(SRC.read_text(encoding="utf-8"))
body = dict(src)
claimed = body.pop("canonical_sha256")
if claimed != EXPECTED_SRC_SHA256 or canonical_sha256(body) != EXPECTED_SRC_SHA256:
    raise SystemExit("raw-order4 Bockstein compact source lock moved")

q = src["quotient_to_raw_bockstein"]
if q != {
    "double_obstruction_rank_f2": 9,
    "quotient_A2_dimension_f2": 26,
    "raw_order2_kernel_dimension_f2": 17,
    "raw_order4_quotient_dimension_f2": 9,
}:
    raise SystemExit(f"unexpected quotient-to-raw dimensions: {q}")
records = src["nine_source_records"]
if len(records) != 9:
    raise SystemExit("expected nine order-four source records")
if any(int(r["raw_residue_exact_order"]) != 4 for r in records):
    raise SystemExit("a Bockstein source lost exact raw order four")
if any(int(r["parent_order"]) != 2 for r in records):
    raise SystemExit("a raw-order4 direction is no longer quotient order two")
if any(not r["complex_conjugation_defect_equals_double_obstruction"] for r in records):
    raise SystemExit("complex-conjugation defect source lock moved")

obstructions = [
    bits_from_hex_le(r["double_obstruction_U44_f2_hex_le"], 44)
    for r in records
]
if rank2(obstructions, 44) != 9:
    raise SystemExit("nine Bockstein images are not independent")

# Use the nine obstruction images as the first nine vectors of a new U44 basis
# and greedily extend with the old standard U44 basis.
new_u44_basis = [row[:] for row in obstructions]
complement_old_indices = []
rank_now = 9
for j in range(44):
    e = [0] * 44
    e[j] = 1
    new_rank = rank2(new_u44_basis + [e], 44)
    if new_rank > rank_now:
        new_u44_basis.append(e)
        complement_old_indices.append(j + 1)
        rank_now = new_rank
if len(new_u44_basis) != 44 or len(complement_old_indices) != 35 or rank_now != 44:
    raise SystemExit("failed to extend Bockstein image to a U44 basis")

inverse = inv2(new_u44_basis)
# Row-vector convention: new_u44_basis rows are new basis vectors in old
# coordinates.  Hash both directions rather than bloating the retained file.
forward_hash = canonical_sha256(new_u44_basis)
inverse_hash = canonical_sha256(inverse)

source_names = [r["source_basis_name"] for r in records]
if source_names != [f"A2_{i:02d}" for i in range(15, 24)]:
    raise SystemExit(f"unexpected order-four source block: {source_names}")

# Exact invariant-factor bookkeeping.  Modulo U44 the 26 chosen lifts are an
# F2 basis.  Seventeen have square zero in the raw extension; nine have
# independent nonzero doubles, now the first nine U44 basis vectors.
order4_factors = 9
order2_factors = (44 - 9) + 17
if order2_factors != 52:
    raise SystemExit("extension invariant-factor bookkeeping regression")
order_log2 = 2 * order4_factors + order2_factors
if order_log2 != 44 + 26:
    raise SystemExit("extension order disagrees with kernel times quotient")

normal_form_pairs = []
for i, r in enumerate(records, 1):
    normal_form_pairs.append({
        "order4_source": r["source_basis_name"],
        "new_u44_double_basis_name": f"U44_BOCK_{i:02d}",
        "double_relation": f"2*{r['source_basis_name']}=U44_BOCK_{i:02d}",
        "complex_conjugation_relation": (
            f"cc({r['source_basis_name']})={r['source_basis_name']}+U44_BOCK_{i:02d}"
        ),
        "complex_conjugation_on_Z4_factor": "inversion",
        "raw_order4_function_package_sha256": r["full_order4_function_package_sha256"],
    })

cert = {
    "schema": "STAGE33_07_ORDER2_RAW_EXTENSION_NORMAL_FORM_V1",
    "source_lock": {
        "raw_order4_bockstein_compact_sha256": EXPECTED_SRC_SHA256,
        "full_raw_order4_bockstein_sha256": src["full_certificate_sha256"],
    },
    "dimensions": {
        "U44_kernel_dimension_f2": 44,
        "quotient_A2_dimension_f2": 26,
        "raw_order2_quotient_kernel_dimension_f2": 17,
        "bockstein_image_dimension_f2": 9,
    },
    "explicit_u44_basis_change": {
        "first_nine_rows_are_order4_source_doubles_in_source_order": source_names,
        "old_u44_standard_basis_complement_indices_1based": complement_old_indices,
        "new_basis_matrix_44x44_sha256": forward_hash,
        "inverse_basis_matrix_44x44_sha256": inverse_hash,
        "new_basis_rank_f2": 44,
    },
    "raw_extension_invariant_factors": {
        "exact_group": "(Z/4)^9 direct_sum (Z/2)^52",
        "order4_factor_count": order4_factors,
        "order2_factor_count": order2_factors,
        "group_order_log2": order_log2,
        "group_order": "2^70",
        "kernel_times_quotient_order_check": "2^44 * 2^26 = 2^70",
    },
    "nine_order4_normal_form_pairs": normal_form_pairs,
    "galois_information_already_forced_by_boundary_extension": {
        "complex_conjugation_on_each_of_nine_Z4_factors": "q -> -q",
        "reason": "cc(q)-q=2q=U44_BOCK_i",
        "sqrt2_conjugation_on_global_Gersten_lift": "NOT_YET_CERTIFIED",
        "G_L_difference_cocycle": "NOT_YET_COMPUTED",
    },
    "exact_checks": {
        "nine_Bockstein_images_independent": True,
        "nine_images_extended_to_full_U44_basis": True,
        "basis_change_invertible_over_F2": True,
        "raw_extension_invariant_factors_exact": True,
        "all_nine_cc_actions_reduce_to_inversion_in_normal_form": True,
        "extension_order_matches_kernel_times_quotient": True,
    },
    "constructive_progress": {
        "quotient_to_raw_Bockstein_extension_normal_form_closed": True,
        "nine_order4_first_residue_function_packages_retained": True,
        "global_geometric_Gersten_lifts_materialized": False,
        "project_14x26_L_squareclass_tensor_materialized": False,
        "absolute_delta_loc_computed": False,
        "arithmetic_HS_closed": False,
    },
    "new_smallest_exact_kernel": "R33-BR2A-9-ORDER4-GERSTEN-LIFT-GALOIS-DIFFERENCE-COCYCLE",
    "next_exact_leaf": "L33-07-MATERIALIZE-9-ORDER4-GLOBAL-GEOMETRIC-GERSTEN-LIFTS-AND-GALOIS-DIFFERENCES",
    "stage33_progress": "6/11",
    "stage33_08_released": False,
    "theorem_credit": False,
    "endpoint_credit": False,
    "perfect_cuboid_existence_claim": False,
    "perfect_cuboid_nonexistence_claim": False,
}
cert["canonical_sha256"] = canonical_sha256(cert)
OUT.write_text(json.dumps(cert, indent=2, sort_keys=True) + "\n", encoding="utf-8")

print(json.dumps({
    "success": True,
    "raw_extension_exact_group": cert["raw_extension_invariant_factors"]["exact_group"],
    "bockstein_image_dimension_f2": 9,
    "u44_complement_dimension_f2": 35,
    "group_order_log2": order_log2,
    "certificate_sha256": cert["canonical_sha256"],
    "new_smallest_exact_kernel": cert["new_smallest_exact_kernel"],
    "next_exact_leaf": cert["next_exact_leaf"],
}, indent=2, sort_keys=True))
