#!/usr/bin/env python3
"""Prepare the complete exact-prefix universe for the k=3 full-Q[4] leaf.

The predecessor certificate has already reduced the k=3 non-elementary branch
of H ~= (Z/4)^3 + (Z/2)^3 to 572,522,496 integral-cc/ct-stable H, compressed
without canonical pruning into 189 exact (P,W) skeleton orbits and affine lift
fibres.  This preparatory leaf reconstructs every one of those affine fibres
from the source equations.

For K=H^perp, R={x in A0:4x in H}, and theta:R->Hom(H,Q/Z), the endpoint
condition |(K/H)[4]|=2^24 is equivalent to

    log2 |im(theta)| = 4-t,

where t=rank(P_X).  Maximal Q[2] implies 2R<=K, hence im(theta) is elementary.
A section-independent subgroup generated by A0[4] and roots of 2(W cap Y)
has exact F2 rank 3 on every one of the 189 skeleton orbits.  Therefore all
t=2 fibres are rejected immediately because their target image rank is 2.

For t=1 the target rank is 3.  We select, for each skeleton orbit, one explicit
theta functional/annihilator pair which is outside the fixed rank-3 subgroup
at the canonical section and at every affine basis direction.  The selection
is NOT used as a completeness argument: the follow-up shards exhaust all
2^d sections in disjoint six-bit prefixes and check the chosen obstruction on
every section, with an exact full-rank fallback if it ever vanishes.

No fast/canonical traversal is used or trusted here.
"""
import hashlib
import json
import runpy
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
PRED_LOCK = 'c18334f94a9b71fc611b7bfdc3c0291125aee09a67ce7267882ae62713847b1b'
SKELETON_LOCK = 'd01faf0f252da478f2ec36d02027b7db4bd74b6bcf6e93a3b5f12169460b3505'
PREFIX_BITS = 6
NVAR = 24
X_MASK = (1 << 10) - 1

# Re-execute the complete predecessor exactly once.  Its own firewall rebuilds
# all 2,628 skeletons, all 189 orbits, all retained cc/ct action choices, and
# the Burnside counts without heuristic representative traversal.
pre_ns = runpy.run_path(str(HERE / 'certify_nonelementary_k3_integral_cc_ct_orbits.py'))
pre = json.loads((HERE / 'nonelementary-k3-integral-cc-ct-orbits.json').read_text())
source = json.loads((HERE / 'nonelementary-k3-q8-skeleton-orbits.json').read_text())
if pre.get('canonical_sha256') != PRED_LOCK:
    raise SystemExit('k3 integral cc/ct predecessor lock moved')
if source.get('canonical_sha256') != SKELETON_LOCK:
    raise SystemExit('k3 skeleton source lock moved')

canon = pre_ns['canon']
complement = pre_ns['complement']
span_coordinate_map = pre_ns['span_coordinate_map']
section_equations = pre_ns['section_equations']
stability_equations = pre_ns['stability_equations']
affine_rref = pre_ns['affine_rref']
cc_matrices = pre_ns['cc_matrices']
rank = pre_ns['ns']['rank']
if len(cc_matrices) != 1024:
    raise SystemExit('retained cc action count regression')
CC = cc_matrices[0]


def free_variables(reduced):
    pivots = set()
    for value in reduced:
        coefficient = int(value) & ((1 << NVAR) - 1)
        pivots.add(coefficient.bit_length() - 1)
    return tuple(i for i in range(NVAR) if i not in pivots)


def solution_from_free(reduced, free_mask):
    free = free_variables(reduced)
    solution = 0
    for j, variable in enumerate(free):
        if (int(free_mask) >> j) & 1:
            solution |= 1 << variable
    for value in reversed(reduced):
        coefficient = int(value) & ((1 << NVAR) - 1)
        pivot = coefficient.bit_length() - 1
        rhs = ((int(value) >> NVAR) & 1) ^ ((coefficient & solution).bit_count() & 1)
        if rhs:
            solution |= 1 << pivot
    for value in reduced:
        coefficient = int(value) & ((1 << NVAR) - 1)
        rhs = (int(value) >> NVAR) & 1
        if ((coefficient & solution).bit_count() & 1) != rhs:
            raise SystemExit('affine solution reconstruction regression')
    return solution


def span_bits(basis):
    out = [0]
    for vector in basis:
        out += [x ^ int(vector) for x in out]
    return out


def pure_y_basis(w_basis):
    return canon(x for x in span_bits(w_basis) if (int(x) & X_MASK) == 0)


def add_mod4(left, right):
    return tuple((int(a) + int(b)) % 4 for a, b in zip(left, right))


def add_selected_rows(rows, coefficient_mask):
    out = (0,) * 14
    for i, row in enumerate(rows):
        if (int(coefficient_mask) >> i) & 1:
            out = add_mod4(out, row)
    return out


def kernel_coefficients(p_basis):
    return canon(
        c for c in range(1, 1 << 3)
        if all(
            sum(((c >> i) & 1) * ((int(p_basis[i]) >> coordinate) & 1)
                for i in range(3)) % 2 == 0
            for coordinate in range(10)
        )
    )


def root_mod4(u):
    root = [0] * 14
    for i in range(10):
        if int(u[i]) % 2:
            raise SystemExit('fourth-root X parity regression')
        root[i] = (int(u[i]) // 2) % 2
    for i in range(10, 14):
        root[i] = int(u[i]) % 4
    return tuple(root)


def functional_mask_even(root, h_generators):
    mask = 0
    for j, h in enumerate(h_generators):
        value = sum(int(root[i]) * int(h[i]) for i in range(14)) % 4
        if value % 2:
            raise SystemExit('theta image lost exponent two under maximal Q[2]')
        if (value // 2) & 1:
            mask |= 1 << j
    return mask


def h_generators(p_basis, w_basis, quotient_basis, solution):
    order_four = []
    for generator, p in enumerate(p_basis):
        correction = 0
        for bit, vector in enumerate(quotient_basis):
            if (int(solution) >> (8 * generator + bit)) & 1:
                correction ^= int(vector)
        order_four.append(tuple(
            (((int(p) >> coordinate) & 1) + 2 * ((correction >> coordinate) & 1)) % 4
            for coordinate in range(14)
        ))
    w_complement = complement(p_basis, w_basis)
    if len(w_complement) != 3:
        raise SystemExit('k3 W/P rank regression')
    order_two = [tuple(2 * ((int(w) >> coordinate) & 1) for coordinate in range(14))
                 for w in w_complement]
    return tuple(order_four + order_two)


def theta_generator_masks(p_basis, w_basis, quotient_basis, solution):
    h = h_generators(p_basis, w_basis, quotient_basis, solution)
    masks = []
    # A0[4] contributes only through the ten Z/8 coordinates modulo four.
    for coordinate in range(10):
        root = [0] * 14
        root[coordinate] = 2
        masks.append(functional_mask_even(tuple(root), h))
    # R/A0[4] is generated by H cap 4A0.  The six 2W generators and the
    # order-four combinations with zero X parity give an exact generating set.
    for w in w_basis:
        u = tuple(2 * ((int(w) >> coordinate) & 1) for coordinate in range(14))
        masks.append(functional_mask_even(root_mod4(u), h))
    for coefficients in kernel_coefficients(p_basis):
        u = add_selected_rows(h[:3], coefficients)
        masks.append(functional_mask_even(root_mod4(u), h))
    return tuple(masks)


def constant_rank3_masks(p_basis, w_basis, quotient_basis, solution):
    h = h_generators(p_basis, w_basis, quotient_basis, solution)
    masks = []
    for coordinate in range(10):
        root = [0] * 14
        root[coordinate] = 2
        masks.append(functional_mask_even(tuple(root), h))
    for w in pure_y_basis(w_basis):
        u = tuple(2 * ((int(w) >> coordinate) & 1) for coordinate in range(14))
        masks.append(functional_mask_even(root_mod4(u), h))
    return canon(masks)


def perp6(basis):
    return canon(
        vector for vector in range(1, 1 << 6)
        if all((int(vector) & int(row)).bit_count() % 2 == 0 for row in basis)
    )

records = []
profile = Counter()
candidate_profile = Counter()
representative_sections = Counter()
weighted_sections = Counter()
for index, representative in enumerate(source['orbit_representatives']):
    p_basis = tuple(int(x) for x in representative['P_basis_bits'])
    w_basis = tuple(int(x) for x in representative['W_basis_bits'])
    orbit_size = int(representative['orbit_size'])
    quotient_basis = complement(w_basis, canon(1 << j for j in range(14)))
    quotient_coordinates = span_coordinate_map(w_basis + quotient_basis)
    base_equations = section_equations(p_basis, quotient_basis)
    extra = stability_equations(p_basis, quotient_basis, quotient_coordinates, CC)
    if extra is None:
        raise SystemExit('retained cc action unexpectedly fails P stability')
    reduced = affine_rref(base_equations + extra)
    if reduced is None:
        raise SystemExit('integral cc/ct fibre became inconsistent')
    dimension = NVAR - len(reduced)
    t = rank([p & X_MASK for p in p_basis])
    if t not in (1, 2) or dimension not in (16, 18, 19, 21):
        raise SystemExit('k3 filtered fibre profile regression')
    section_count = 1 << dimension
    representative_sections[t] += section_count
    weighted_sections[t] += orbit_size * section_count

    canonical_solution = solution_from_free(reduced, 0)
    fixed = constant_rank3_masks(p_basis, w_basis, quotient_basis, canonical_solution)
    if len(fixed) != 3:
        raise SystemExit(f'fixed theta subgroup rank regression at skeleton {index}: {len(fixed)}')
    # The fixed generators are section-independent; verify on every affine
    # basis direction while selecting the prefix obstruction.
    free_count = len(free_variables(reduced))
    if free_count != dimension:
        raise SystemExit('free-variable dimension regression')
    unit_solutions = [solution_from_free(reduced, 1 << j) for j in range(free_count)]
    for solution in unit_solutions:
        if constant_rank3_masks(p_basis, w_basis, quotient_basis, solution) != fixed:
            raise SystemExit('section-independent rank-3 theta subgroup moved')

    record = {
        'skeleton_orbit_index': index,
        'skeleton_orbit_size': orbit_size,
        't': t,
        'target_theta_image_rank': 4 - t,
        'fixed_theta_subgroup_rank': 3,
        'integral_cc_ct_lift_dimension': dimension,
        'integral_cc_ct_lift_count': section_count,
        'P_basis_bits': list(p_basis),
        'W_basis_bits': list(w_basis),
        'quotient_basis_bits': list(quotient_basis),
        'filtered_affine_rref_augmented': [int(x) for x in reduced],
    }
    if t == 2:
        record['rejection_kind'] = 'fixed-rank-3-exceeds-target-rank-2'
    else:
        annihilator = perp6(fixed)
        if len(annihilator) != 3:
            raise SystemExit('fixed rank-3 annihilator regression')
        base_masks = theta_generator_masks(p_basis, w_basis, quotient_basis, canonical_solution)
        unit_masks = [theta_generator_masks(p_basis, w_basis, quotient_basis, solution)
                      for solution in unit_solutions]
        selected = None
        for generator_index, base_mask in enumerate(base_masks):
            for y in annihilator:
                if (int(base_mask) & int(y)).bit_count() % 2 != 1:
                    continue
                if all((int(masks[generator_index]) & int(y)).bit_count() % 2 == 1
                       for masks in unit_masks):
                    selected = (generator_index, int(y))
                    break
            if selected is not None:
                break
        if selected is None:
            raise SystemExit(f'no prefix obstruction selector at t=1 skeleton {index}')
        generator_index, annihilator_mask = selected
        candidate_profile[(generator_index, annihilator_mask)] += 1
        record.update({
            'rejection_kind': 'exact-prefix-check-selected-outside-fixed-rank3',
            'prefix_bits': PREFIX_BITS,
            'prefix_count': 1 << PREFIX_BITS,
            'selected_theta_generator_index': generator_index,
            'selected_fixed_annihilator_mask': annihilator_mask,
            'selector_checked_at_canonical_and_all_affine_basis_directions': True,
            'selector_completeness_claimed': False,
        })
    records.append(record)
    profile[(t, dimension, orbit_size)] += 1

if len(records) != 189:
    raise SystemExit('k3 skeleton-orbit manifest count regression')
if representative_sections != Counter({1: 7471104, 2: 41680896}):
    raise SystemExit(f'representative section reconstruction regression {representative_sections}')
if weighted_sections != Counter({1: 108527616, 2: 463994880}):
    raise SystemExit(f'weighted predecessor reconstruction regression {weighted_sections}')
if sum(weighted_sections.values()) != 572522496:
    raise SystemExit('integral cc/ct predecessor total regression')
if sum(1 for r in records if r['t'] == 1) != 72 or sum(1 for r in records if r['t'] == 2) != 117:
    raise SystemExit('t-profile skeleton orbit regression')
if candidate_profile != Counter({(14, 32): 36, (16, 16): 19, (16, 8): 17}):
    raise SystemExit(f'prefix obstruction selector profile regression {candidate_profile}')

prefix_task_count = 72 * (1 << PREFIX_BITS)
cert = {
    'schema': 'STAGE33_07_NONELEMENTARY_K3_Q4_PREFIX_MANIFEST_V1',
    'source_integral_cc_ct_sha256': PRED_LOCK,
    'source_k3_skeleton_orbits_sha256': SKELETON_LOCK,
    'abstract_H_type': '(Z/4)^3 direct_sum (Z/2)^3',
    'theta_definition': 'R={x:4x in H}; theta(x)(h)=4*b(x,h) in Z/4; maximal Q[2] forces exponent(theta image)<=2',
    'target_theta_image_rank_formula': 'rank_F2 im(theta)=4-t iff |(Hperp/H)[4]|=2^24',
    'fixed_theta_subgroup_rank_every_skeleton': 3,
    't2_skeleton_orbits_rejected_without_section_enumeration': 117,
    't1_skeleton_orbits_exact_prefix_checked': 72,
    'prefix_bits': PREFIX_BITS,
    't1_prefix_task_count': prefix_task_count,
    't1_representative_section_count': representative_sections[1],
    't2_representative_section_count': representative_sections[2],
    'representative_section_count_total': sum(representative_sections.values()),
    't1_weighted_structural_H_count': weighted_sections[1],
    't2_weighted_structural_H_count': weighted_sections[2],
    'weighted_structural_H_count_total': sum(weighted_sections.values()),
    'candidate_selector_profile': {
        f'generator={g},annihilator={y}': n for (g, y), n in sorted(candidate_profile.items())
    },
    'records': records,
    'prefix_sharding_disjointness_and_coverage_required': True,
    'predecessor_reconstructed_exactly': True,
    'fast_or_heuristic_traversal_used': False,
    'canonical_augmentation_completeness_claimed': False,
    'full_Q4_condition_certified': False,
    'k3_abstract_type_rejected': False,
    'endpoint_finite_q_certified': False,
    'endpoint_full_action_conjugacy_certified': False,
    'actual_index512_glue_identified': False,
    'arithmetic_HS_closed': False,
    'stage33_progress': '6/11',
    'stage33_08_released': False,
    'stage33_09_released': False,
    'endpoint_credit': False,
    'perfect_cuboid_nonexistence_claim': False,
}
raw = json.dumps(cert, sort_keys=True, separators=(',', ':')).encode()
cert['canonical_sha256'] = hashlib.sha256(raw).hexdigest()
(HERE / 'nonelementary-k3-q4-prefix-manifest.json').write_text(
    json.dumps(cert, indent=2, sort_keys=True) + '\n')
print(json.dumps({
    'success': True,
    'skeleton_orbits': 189,
    't1_orbits': 72,
    't2_orbits': 117,
    't1_prefix_tasks': prefix_task_count,
    't1_representative_sections': representative_sections[1],
    't2_weighted_immediate_rejections': weighted_sections[2],
    'manifest_sha256': cert['canonical_sha256'],
}, indent=2, sort_keys=True))
