#!/usr/bin/env python3
"""Map two-face cuboids to specialized elliptic curves and audit exact relations.

The face-cuboid K3 surface is fibered by the parameter

    lambda = (Y - A) / C = C / (Y + A).

For a smooth fiber, van Luijk's Weierstrass model is

    y^2 z = x (x + 4 lambda^2 z) (x + (lambda^2 + 1)^2 z),

with inverse map from the standard face-cuboid coordinates

    x = 4 lambda^2 C (U - B),
    y = 8 lambda^3 (U + X) (U - B),
    z = C (X + B).

This script performs exact rational arithmetic. It verifies the map for every
record, computes the generic rational torsion subgroup generated by T1 and T3,
and searches for bounded integral relations among the observed points on each
repeated fiber. A bounded-search basis is only a finite-data certificate; it
is not a proof of the Mordell-Weil rank or a full set of generators.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from fractions import Fraction
from itertools import product
from pathlib import Path
from typing import Any


DEFAULT_INPUT = Path("data/two_face_cuboids_1e6_kummer_classification.json")
Point = tuple[Fraction, Fraction] | None


def parse_fraction(record: dict[str, Any]) -> Fraction:
    return Fraction(int(record["numerator"]), int(record["denominator"]))


def fraction_record(value: Fraction) -> dict[str, int | str]:
    return {
        "numerator": value.numerator,
        "denominator": value.denominator,
        "text": str(value.numerator)
        if value.denominator == 1
        else f"{value.numerator}/{value.denominator}",
    }


def point_record(point: Point) -> dict[str, Any]:
    if point is None:
        return {"infinity": True}
    return {
        "infinity": False,
        "x": fraction_record(point[0]),
        "y": fraction_record(point[1]),
    }


def curve_coefficients(lam: Fraction) -> tuple[Fraction, Fraction]:
    a2 = 4 * lam * lam + (lam * lam + 1) ** 2
    a4 = 4 * lam * lam * (lam * lam + 1) ** 2
    return a2, a4


def point_on_curve(point: Point, lam: Fraction) -> bool:
    if point is None:
        return True
    x, y = point
    a2, a4 = curve_coefficients(lam)
    return y * y == x**3 + a2 * x * x + a4 * x


def point_neg(point: Point) -> Point:
    return None if point is None else (point[0], -point[1])


def point_add(left: Point, right: Point, lam: Fraction) -> Point:
    if left is None:
        return right
    if right is None:
        return left
    x1, y1 = left
    x2, y2 = right
    a2, a4 = curve_coefficients(lam)
    if x1 == x2 and y1 == -y2:
        return None
    if left == right:
        if y1 == 0:
            return None
        slope = (3 * x1 * x1 + 2 * a2 * x1 + a4) / (2 * y1)
    else:
        slope = (y2 - y1) / (x2 - x1)
    x3 = slope * slope - a2 - x1 - x2
    y3 = -y1 + slope * (x1 - x3)
    result = (x3, y3)
    if not point_on_curve(result, lam):
        raise ArithmeticError("group-law result failed the Weierstrass equation")
    return result


def point_mul(multiplier: int, point: Point, lam: Fraction) -> Point:
    if multiplier < 0:
        return point_mul(-multiplier, point_neg(point), lam)
    result: Point = None
    addend = point
    value = multiplier
    while value:
        if value & 1:
            result = point_add(result, addend, lam)
        addend = point_add(addend, addend, lam)
        value >>= 1
    return result


def map_standard_to_weierstrass(
    standard: dict[str, int], lam: Fraction
) -> tuple[Point, dict[str, Any]]:
    A, B, C, X, Y, U = (int(standard[key]) for key in "ABCXYU")
    xp = 4 * lam * lam * C * (U - B)
    yp = 8 * lam**3 * (U + X) * (U - B)
    zp = C * (X + B)
    point: Point = None if zp == 0 else (xp / zp, yp / zp)
    return point, {
        "x": fraction_record(xp),
        "y": fraction_record(yp),
        "z": fraction_record(zp),
    }


def generic_torsion_subgroup(lam: Fraction) -> list[dict[str, Any]]:
    t1: Point = (
        2 * lam * (lam * lam + 1),
        2 * lam * (lam * lam + 1) * (lam + 1) ** 2,
    )
    t3: Point = (-4 * lam * lam, Fraction(0))
    entries: list[dict[str, Any]] = []
    seen: set[Point] = set()
    for coefficient_t1 in range(4):
        for coefficient_t3 in range(2):
            point = point_add(
                point_mul(coefficient_t1, t1, lam),
                point_mul(coefficient_t3, t3, lam),
                lam,
            )
            if point in seen:
                continue
            seen.add(point)
            entries.append(
                {
                    "label": f"{coefficient_t1}T1+{coefficient_t3}T3",
                    "coefficient_T1_mod_4": coefficient_t1,
                    "coefficient_T3_mod_2": coefficient_t3,
                    "point": point,
                }
            )
    if len(entries) != 8:
        raise ArithmeticError(
            f"expected eight generic torsion points, obtained {len(entries)}"
        )
    return entries


def finite_order_up_to(point: Point, lam: Fraction, limit: int) -> int | None:
    if point is None:
        return 1
    for order in range(1, limit + 1):
        if point_mul(order, point, lam) is None:
            return order
    return None


def find_bounded_relation(
    target: Point,
    basis: list[Point],
    torsion: list[dict[str, Any]],
    lam: Fraction,
    bound: int,
) -> dict[str, Any] | None:
    if not basis:
        for torsion_entry in torsion:
            if torsion_entry["point"] == target:
                return {
                    "coefficients": [],
                    "torsion_label": torsion_entry["label"],
                }
        return None
    multiples = [
        {
            coefficient: point_mul(coefficient, basis_point, lam)
            for coefficient in range(-bound, bound + 1)
        }
        for basis_point in basis
    ]
    for coefficients in product(range(-bound, bound + 1), repeat=len(basis)):
        subtotal: Point = None
        for basis_index, coefficient in enumerate(coefficients):
            subtotal = point_add(
                subtotal, multiples[basis_index][coefficient], lam
            )
        for torsion_entry in torsion:
            if point_add(subtotal, torsion_entry["point"], lam) == target:
                return {
                    "coefficients": list(coefficients),
                    "torsion_label": torsion_entry["label"],
                }
    return None


def classify_fiber(
    lam_text: str,
    items: list[dict[str, Any]],
    relation_bound: int,
    max_basis_size: int,
    torsion_order_limit: int,
) -> dict[str, Any]:
    lam = Fraction(lam_text)
    torsion = generic_torsion_subgroup(lam)
    points: list[Point] = [item["weierstrass_point_internal"] for item in items]
    basis: list[Point] = []
    basis_source_indices: list[int] = []
    for item, point in zip(items, points):
        relation = find_bounded_relation(
            point, basis, torsion, lam, relation_bound
        )
        if relation is None and len(basis) < max_basis_size:
            basis.append(point)
            basis_source_indices.append(int(item["source_index"]))
    final_relations: list[dict[str, Any]] = []
    for item, point in zip(items, points):
        relation = find_bounded_relation(
            point, basis, torsion, lam, relation_bound
        )
        final_relations.append(
            {"source_index": int(item["source_index"]), "relation": relation}
        )
    pairwise_torsion_differences: list[dict[str, Any]] = []
    for left_index, left in enumerate(points):
        for right_index in range(left_index + 1, len(points)):
            difference = point_add(points[right_index], point_neg(left), lam)
            order = finite_order_up_to(difference, lam, torsion_order_limit)
            if order is not None:
                pairwise_torsion_differences.append(
                    {
                        "left_source_index": int(items[left_index]["source_index"]),
                        "right_source_index": int(items[right_index]["source_index"]),
                        "difference_order": order,
                    }
                )
    a2, a4 = curve_coefficients(lam)
    return {
        "lambda": lam_text,
        "lambda_fraction": fraction_record(lam),
        "curve": {
            "equation": "y^2=x(x+4*lambda^2)(x+(lambda^2+1)^2)",
            "a2": fraction_record(a2),
            "a4": fraction_record(a4),
        },
        "point_count": len(items),
        "source_indices": [int(item["source_index"]) for item in items],
        "generic_rational_torsion": [
            {
                "label": entry["label"],
                "coefficient_T1_mod_4": entry["coefficient_T1_mod_4"],
                "coefficient_T3_mod_2": entry["coefficient_T3_mod_2"],
                "point": point_record(entry["point"]),
            }
            for entry in torsion
        ],
        "bounded_relation_search": {
            "coefficient_bound": relation_bound,
            "max_basis_size": max_basis_size,
            "basis_source_indices": basis_source_indices,
            "bounded_basis_size": len(basis),
            "all_observed_points_certified": all(
                entry["relation"] is not None for entry in final_relations
            ),
            "relations": final_relations,
            "unclassified_source_indices": [
                entry["source_index"]
                for entry in final_relations
                if entry["relation"] is None
            ],
            "warning": (
                "This is a bounded exact relation search among observed points. "
                "The bounded basis size is not a Mordell-Weil rank proof."
            ),
        },
        "observed_point_orders_up_to_limit": {
            "limit": torsion_order_limit,
            "orders": {
                str(item["source_index"]): finite_order_up_to(
                    point, lam, torsion_order_limit
                )
                for item, point in zip(items, points)
            },
        },
        "pairwise_torsion_differences_up_to_limit": pairwise_torsion_differences,
    }


def analyze(
    input_path: Path,
    relation_bound: int,
    max_basis_size: int,
    torsion_order_limit: int,
) -> tuple[dict[str, Any], dict[str, Any]]:
    payload = json.loads(input_path.read_text(encoding="utf-8"))
    source_points = payload.get("points", [])
    errors: list[str] = []
    enriched: list[dict[str, Any]] = []
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for item in source_points:
        source_index = int(item["source_index"])
        affine = item["elliptic_fibration_parameter"].get("affine")
        if affine is None:
            errors.append(f"source_index={source_index}: missing affine lambda")
            continue
        lam = parse_fraction(affine)
        expected_lam = Fraction(
            int(item["standard_coordinates"]["Y"])
            - int(item["standard_coordinates"]["A"]),
            int(item["standard_coordinates"]["C"]),
        )
        if lam != expected_lam:
            errors.append(f"source_index={source_index}: lambda mismatch")
        point, projective = map_standard_to_weierstrass(
            item["standard_coordinates"], lam
        )
        valid = point_on_curve(point, lam)
        if not valid:
            errors.append(
                f"source_index={source_index}: Weierstrass equation failed"
            )
        record = {
            "source_index": source_index,
            "source_tuple": item["source_tuple"],
            "lambda": affine["text"],
            "weierstrass_projective": projective,
            "weierstrass_point": point_record(point),
            "weierstrass_equation_valid": valid,
            "observed_point_order_up_to_limit": finite_order_up_to(
                point, lam, torsion_order_limit
            ),
            "weierstrass_point_internal": point,
        }
        enriched.append(record)
        grouped[str(affine["text"])].append(record)
    repeated = {
        lam_text: items
        for lam_text, items in grouped.items()
        if len(items) > 1
    }
    fibers = [
        classify_fiber(
            lam_text,
            items,
            relation_bound,
            max_basis_size,
            torsion_order_limit,
        )
        for lam_text, items in sorted(
            repeated.items(), key=lambda pair: Fraction(pair[0])
        )
    ]
    for record in enriched:
        record.pop("weierstrass_point_internal", None)
    basis_histogram = Counter(
        fiber["bounded_relation_search"]["bounded_basis_size"]
        for fiber in fibers
    )
    focus = next((fiber for fiber in fibers if fiber["lambda"] == "16/21"), None)
    derived = {
        "metadata": {
            "source": input_path.as_posix(),
            "point_count": len(enriched),
            "relation_bound": relation_bound,
            "max_basis_size": max_basis_size,
            "torsion_order_limit": torsion_order_limit,
            "method_scope": {
                "proved": [
                    "the van Luijk coordinate map lands on the specialized Weierstrass curve",
                    "all listed bounded relations are exact rational group-law identities",
                    "the listed generic torsion subgroup has eight distinct specialized points",
                ],
                "not_proved": [
                    "the full Mordell-Weil rank of a specialized fiber",
                    "that the bounded-search basis is a Mordell-Weil basis",
                    "that no relation exists outside the coefficient bound",
                    "any asymptotic upper bound for N_2(B)",
                ],
            },
        },
        "points": enriched,
        "repeated_fibers": fibers,
    }
    report = {
        "valid": not errors,
        "source": input_path.as_posix(),
        "point_count": len(enriched),
        "weierstrass_equation_valid_count": sum(
            record["weierstrass_equation_valid"] for record in enriched
        ),
        "observed_finite_order_point_count_up_to_limit": sum(
            record["observed_point_order_up_to_limit"] is not None
            for record in enriched
        ),
        "torsion_order_limit": torsion_order_limit,
        "repeated_fiber_count": len(fibers),
        "fully_certified_repeated_fiber_count": sum(
            bool(fiber["bounded_relation_search"]["all_observed_points_certified"])
            for fiber in fibers
        ),
        "bounded_basis_size_histogram": {
            str(size): count for size, count in sorted(basis_histogram.items())
        },
        "focus_lambda_16_21": focus,
        "interpretation": {
            "bounded_basis_size": (
                "number of observed seed points needed so that every observed "
                "point found by the bounded search is an integral combination "
                "of those seeds plus generic rational torsion"
            ),
            "warning": (
                "This finite exact relation certificate is not a proof of the "
                "specialized Mordell-Weil rank or of a complete generator set."
            ),
        },
        "errors": errors,
    }
    return derived, report


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--relation-bound", type=int, default=8)
    parser.add_argument("--max-basis-size", type=int, default=3)
    parser.add_argument("--torsion-order-limit", type=int, default=24)
    parser.add_argument("--write-derived", type=Path)
    parser.add_argument("--write-report", type=Path)
    args = parser.parse_args()
    if args.relation_bound < 1 or args.max_basis_size < 1:
        parser.error("relation bound and max basis size must be positive")
    if args.torsion_order_limit < 1:
        parser.error("torsion order limit must be positive")
    derived, report = analyze(
        args.input,
        args.relation_bound,
        args.max_basis_size,
        args.torsion_order_limit,
    )
    derived_text = json.dumps(derived, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    report_text = json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    if args.write_derived:
        args.write_derived.parent.mkdir(parents=True, exist_ok=True)
        args.write_derived.write_text(derived_text, encoding="utf-8")
    if args.write_report:
        args.write_report.parent.mkdir(parents=True, exist_ok=True)
        args.write_report.write_text(report_text, encoding="utf-8")
    if not args.write_derived and not args.write_report:
        print(report_text, end="")
    return 0 if report["valid"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
