#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import itertools
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
B3B2 = HERE / "e3-v91c1x-r5b3b2-a2-02-formal-tame-symbol-hidden-carrier-inventory.json"
C1 = HERE / "e3-v91c1x-r5b3b3c1-offboundary-norm-factorization.json"
C2C = HERE / "e3-v91c1x-r5b3b3c2c-orbit-representative-strict-prime-decomposition-and-transport.json"
C4A = HERE / "e3-v91c1x-r5b3b3c4a-tame-residue-parity-and-cross-carrier-preflight.json"
H2 = HERE / "e3-v91c1x-r5b3b3c4b1e5h2-squareclass-gauge-to-a2-02-representative-binding-audit.json"
OUT = HERE / "e3-v91c1x-r5b3b3c4b2a-strict-prime-cross-carrier-geometric-incidence.json"

B3B2_SHA = "52429d1197e1383daef8c25acdb1224822d7f5c22ecb7046c8b47766438a547e"
C1_SHA = "5c092fcec6720d0097d6e7509ce37b1506d7a099015a1a6a004250513d0f29f3"
C2C_SHA = "01fc321272106a1ce7c382783c4dcb128c164d21ee4deedf4060137ef9ed971a"
C4A_SHA = "fab3f7b1235370a3916b99b6909cd6c6363193ff271ee6b51cb9494b0668e525"
H2_SHA = "6fd0fe9ffd666c21c394dc3a0a0fc6e03cea6936af26d4d9e84b3a29cbccbe9c"
AUTHORITY = "V91C1V_A2_02_ACTUAL_PRIME_KNOWN140_LOCATOR_BOUNDED_RESULT"
SPECIAL_LINEAR = "44afff33ba591a11904229fe7936cb41caa700bd759cda0a5106218250561491"
SPECIAL_RESIDUAL = "da9c1c762b7deb1ac7c630325bcfa1ee9b1a44916f5bd9df410bf16c9effd5b4"
PAIR_FACTOR = "69623aeb5f2dab057c7c435c9f72d85b6670e7716c1a64d2a2b8ea3b9ec1be1b"
SPECIAL = {
    "LIN_008": {"b2_sign": -1, "b3_sign": -1},
    "LIN_015": {"b2_sign": 1, "b3_sign": -1},
    "LIN_020": {"b2_sign": -1, "b3_sign": 1},
    "LIN_025": {"b2_sign": 1, "b3_sign": 1},
}
EXPECTED_REAL_COEFFS = {
    "LIN_008": [1, 2, 4, 8, 4, 2, -8],
    "LIN_015": [1, 2, 4, 8, -4, 2, -8],
    "LIN_020": [1, 2, 4, 8, 4, -2, -8],
    "LIN_025": [1, 2, 4, 8, -4, -2, -8],
    "LIN_013": [0, 0, 0, 0, 1, 1, -1],
    "LIN_019": [0, 0, 0, 0, 1, -1, 1],
}


def csha(obj: object) -> str:
    return hashlib.sha256(json.dumps(obj, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


def load_locked(path: Path, expected: str) -> dict:
    obj = json.loads(path.read_text(encoding="utf-8"))
    body = dict(obj)
    claimed = body.pop("canonical_sha256", None)
    actual = csha(body)
    if claimed != expected or actual != expected:
        raise SystemExit(f"canonical source lock moved {path.name}: claimed={claimed} actual={actual} expected={expected}")
    return obj


def real_coeffs(row: dict) -> list[int]:
    out = []
    for z in row["normalized_coefficients_Qi"]:
        if [int(z[1]), int(z[2]), int(z[3])] != [1, 0, 1]:
            raise SystemExit(f"expected integral real normalized coefficient on {row['carrier_id']}: {z}")
        out.append(int(z[0]))
    return out


def c1_factor(c1_by_id: dict, cid: str, fsha: str) -> dict:
    matches = [f for f in c1_by_id[cid]["factors"] if f["normalized_factor_sha256"] == fsha]
    if len(matches) != 1:
        raise SystemExit(f"C1 factor lookup not unique: {cid} {fsha}")
    return matches[0]


def boundary_pair_witness(cid1: str, cid2: str) -> dict:
    s1, s2 = SPECIAL[cid1], SPECIAL[cid2]
    if s1["b2_sign"] != s2["b2_sign"]:
        return {
            "carrier_pair": [cid1, cid2],
            "shared_prime_would_force_base_polynomial": "a3",
            "base_polynomial_degree": 1,
            "base_factor": "a1",
            "base_factor_degree": 1,
            "nonmembership_reason": "a3 and a1 are nonassociate linear forms in Q(i)[a1,a2,a3]",
        }
    if s1["b3_sign"] != s2["b3_sign"]:
        return {
            "carrier_pair": [cid1, cid2],
            "shared_prime_would_force_base_polynomial": "a2",
            "base_polynomial_degree": 1,
            "base_factor": "a1",
            "base_factor_degree": 1,
            "nonmembership_reason": "a2 and a1 are nonassociate linear forms in Q(i)[a1,a2,a3]",
        }
    raise SystemExit(f"duplicate special sign row: {cid1} {cid2}")


def residual_pair_witness(cid1: str, cid2: str) -> dict:
    s1, s2 = SPECIAL[cid1], SPECIAL[cid2]
    b2diff = s1["b2_sign"] != s2["b2_sign"]
    b3diff = s1["b3_sign"] != s2["b3_sign"]
    if b2diff and not b3diff:
        relation, base_poly = "b2=0", "a1^2+a3^2"
    elif b3diff and not b2diff:
        relation, base_poly = "b3=0", "a1^2+a2^2"
    elif b2diff and b3diff:
        relation, base_poly = "2*b2 +/- b3=0", "3*a1^2-a2^2+4*a3^2"
    else:
        raise SystemExit(f"duplicate special sign row: {cid1} {cid2}")
    return {
        "carrier_pair": [cid1, cid2],
        "shared_residual_prime_would_force_root_relation": relation,
        "surface_square_relations_force_base_polynomial": base_poly,
        "base_polynomial_degree": 2,
        "residual_base_factor": "F14",
        "residual_base_factor_degree": 14,
        "nonmembership_reason": "a nonzero degree-2 polynomial cannot lie in the principal prime generated by irreducible degree-14 F14",
    }


def build_certificate() -> dict:
    b3b2 = load_locked(B3B2, B3B2_SHA)
    c1 = load_locked(C1, C1_SHA)
    c2c = load_locked(C2C, C2C_SHA)
    c4a = load_locked(C4A, C4A_SHA)
    h2 = load_locked(H2, H2_SHA)
    if h2["next_exact_leaf"] != "V91C1X_R5B3B3C4B2_STRICT_PRIME_CROSS_CARRIER_INCIDENCE_AND_RESIDUE_FIELD_SQUARECLASS_REDUCTION":
        raise SystemExit("H2 handoff moved")

    pre = c4a["strict_prime_preflight"]
    repeated = pre["repeated_factor_groups"]
    if pre["carrier_factor_incidence_row_count"] != 28:
        raise SystemExit("C4A strict context count moved")
    if len(repeated) != 3 or pre["repeated_factor_context_row_count_requiring_cross_carrier_geometric_incidence"] != 10:
        raise SystemExit("C4A repeated-factor inventory moved")
    by_factor = {r["c1_normalized_factor_sha256"]: r for r in repeated}
    if set(by_factor) != {SPECIAL_LINEAR, SPECIAL_RESIDUAL, PAIR_FACTOR}:
        raise SystemExit("C4A repeated factor identities moved")
    if sorted(by_factor[SPECIAL_LINEAR]["carrier_ids"]) != sorted(SPECIAL):
        raise SystemExit("C4A a1 carrier set moved")
    if sorted(by_factor[SPECIAL_RESIDUAL]["carrier_ids"]) != sorted(SPECIAL):
        raise SystemExit("C4A F14 carrier set moved")
    if sorted(by_factor[PAIR_FACTOR]["carrier_ids"]) != ["LIN_013", "LIN_019"]:
        raise SystemExit("C4A F4 pair carrier set moved")

    carrier_rows = b3b2["finite_linear_carrier_inventory"]["carrier_rows"]
    carriers = {r["carrier_id"]: r for r in carrier_rows}
    for cid, expected in EXPECTED_REAL_COEFFS.items():
        if real_coeffs(carriers[cid]) != expected:
            raise SystemExit(f"carrier linear form moved: {cid}")

    c1_by_id = {r["carrier_id"]: r for r in c1["exact_factorization"]["carrier_rows"]}
    for cid in SPECIAL:
        a1f = c1_factor(c1_by_id, cid, SPECIAL_LINEAR)
        f14 = c1_factor(c1_by_id, cid, SPECIAL_RESIDUAL)
        if (int(a1f["factor_total_degree"]), int(a1f["multiplicity"])) != (1, 2):
            raise SystemExit(f"special a1 factor moved: {cid}")
        if (int(f14["factor_total_degree"]), int(f14["multiplicity"])) != (14, 1):
            raise SystemExit(f"special F14 factor moved: {cid}")
    for cid in ("LIN_013", "LIN_019"):
        f4 = c1_factor(c1_by_id, cid, PAIR_FACTOR)
        if (int(f4["factor_total_degree"]), int(f4["multiplicity"])) != (4, 4):
            raise SystemExit(f"pair F4 factor moved: {cid}")

    rep_rows = {r["carrier_id"]: r for r in c2c["representative_strict_prime_decompositions"]["rows"]}
    for cid in SPECIAL:
        cert = rep_rows[cid]["special_reducible_norm_prime_decomposition_certificate"]
        if not cert["boundary_prime"]["quotient_is_domain"]:
            raise SystemExit(f"special boundary domain proof moved: {cid}")
        if not cert["residual_prime"]["unique_minimal_prime_above_factor"]:
            raise SystemExit(f"special residual uniqueness moved: {cid}")
        if cert["residual_prime"]["base_factor"] != "F14" or int(cert["residual_prime"]["local_multiplicity"]) != 1:
            raise SystemExit(f"special residual prime contract moved: {cid}")

    context_rows = [r for r in pre["rows"] if r["c1_factor_repeated_across_carrier_contexts"]]
    if len(context_rows) != 10:
        raise SystemExit("C4A repeated context rows moved")
    context_by_key = {(r["c1_normalized_factor_sha256"], r["carrier_id"]): r for r in context_rows}
    if len(context_by_key) != 10:
        raise SystemExit("C4A repeated context key collision")

    boundary_witnesses = [boundary_pair_witness(a, b) for a, b in itertools.combinations(sorted(SPECIAL), 2)]
    residual_witnesses = [residual_pair_witness(a, b) for a, b in itertools.combinations(sorted(SPECIAL), 2)]
    pair_witness = {
        "carrier_pair": ["LIN_013", "LIN_019"],
        "linear_forms": ["b2+b3-c", "b2-b3+c"],
        "shared_prime_would_force_root_relation": "b2=0 (sum of the two carrier equations)",
        "surface_square_relation_forces_base_polynomial": "a1^2+a3^2",
        "base_polynomial_degree": 2,
        "repeated_base_factor": "F4",
        "repeated_base_factor_degree": 4,
        "nonmembership_reason": "a nonzero degree-2 polynomial cannot lie in the principal prime generated by irreducible degree-4 F4",
    }

    proof_by_factor = {
        SPECIAL_LINEAR: {
            "method": "C2C_EXPLICIT_BOUNDARY_PRIMES_PLUS_BASE_CONTRACTION_NONASSOCIATE_LINEAR_WITNESSES",
            "factor_degree": 1,
            "pairwise_separation_witnesses": boundary_witnesses,
        },
        SPECIAL_RESIDUAL: {
            "method": "C2C_UNIQUE_F14_RESIDUAL_PRIMES_PLUS_LOW_DEGREE_BASE_CONTRACTION_WITNESSES_FROM_CARRIER_DIFFERENCES",
            "factor_degree": 14,
            "pairwise_separation_witnesses": residual_witnesses,
        },
        PAIR_FACTOR: {
            "method": "LOW_DEGREE_BASE_CONTRACTION_WITNESS_FROM_THE_TWO_EXACT_LINEAR_CARRIER_EQUATIONS",
            "factor_degree": 4,
            "pairwise_separation_witnesses": [pair_witness],
        },
    }

    group_rows = []
    zero_parity = 0
    nonzero_parity = 0
    for fsha in (SPECIAL_LINEAR, SPECIAL_RESIDUAL, PAIR_FACTOR):
        ids = sorted(by_factor[fsha]["carrier_ids"])
        clusters = []
        for k, cid in enumerate(ids, 1):
            row = context_by_key[(fsha, cid)]
            if row["single_carrier_valuation_candidate"] != {cid: 1}:
                raise SystemExit(f"C4A singleton valuation moved: {fsha} {cid}")
            odd = list(row["combined_tame_residue_odd_linear_carrier_ids_under_single_carrier_valuation"])
            is_zero = bool(row["combined_tame_residue_carrier_parity_zero_under_single_carrier_valuation"])
            if is_zero != (not odd):
                raise SystemExit(f"C4A parity encoding inconsistent: {fsha} {cid}")
            zero_parity += int(is_zero)
            nonzero_parity += int(not is_zero)
            clusters.append({
                "geometric_prime_cluster_index": k,
                "incident_carrier_ids_exact": [cid],
                "incident_carrier_count": 1,
                "c4a_strict_prime_id_retained_for_traceability_not_used_for_distinctness": list(row["strict_prime_ids"]),
                "combined_tame_residue_odd_linear_carrier_ids": odd,
                "combined_tame_residue_carrier_parity_zero": is_zero,
                "tame_sign_parity": int(row["tame_sign_parity"]),
                "squareclass_status": "SQUARE_TRIVIAL_BY_EVEN_LINEAR_FACTOR_PARITY" if is_zero else "REQUIRES_TARGETED_RESIDUE_FIELD_SQUARECLASS_REDUCTION",
            })
        group_rows.append({
            "c1_normalized_factor_sha256": fsha,
            "context_carrier_ids": ids,
            "context_count": len(ids),
            "geometrically_distinct_strict_prime_count": len(ids),
            "all_contexts_pairwise_distinct": True,
            "exact_distinctness_proof": proof_by_factor[fsha],
            "clusters": clusters,
        })

    unique_rows = [r for r in pre["rows"] if not r["c1_factor_repeated_across_carrier_contexts"]]
    if len(unique_rows) != 18:
        raise SystemExit(f"C4A unique-factor row count moved: {len(unique_rows)}")
    unique_nonzero = sum(not bool(r["combined_tame_residue_carrier_parity_zero_under_single_carrier_valuation"]) for r in unique_rows)
    if unique_nonzero != 18:
        raise SystemExit(f"C4A unique-factor nonzero parity count moved: {unique_nonzero}")
    if zero_parity != 0 or nonzero_parity != 10:
        raise SystemExit(f"repeated-context parity partition moved: zero={zero_parity} nonzero={nonzero_parity}")

    cert = {
        "schema": "stage33.e3.v91c1x_r5b3b3c4b2a.strict_prime_cross_carrier_geometric_incidence.v2",
        "stage": "33-12",
        "candidate": "V91C1X_R5B3B3C4B2A_STRICT_PRIME_CROSS_CARRIER_GEOMETRIC_INCIDENCE",
        "role": "EXACT_NONCREDIT_BASE_CONTRACTION_RESOLUTION_OF_THE_10_C4A_REPEATED_FACTOR_CONTEXTS_WITHOUT_RECOMPUTING_HEAVY_SEVEN_VARIABLE_SATURATIONS",
        "entry": {"authority": AUTHORITY, "stage33_progress": "6/11", "successor_pr": 1722},
        "source_locks": {
            "r5b3b2_sha256": B3B2_SHA,
            "r5b3b3c1_sha256": C1_SHA,
            "r5b3b3c2c_sha256": C2C_SHA,
            "c4a_sha256": C4A_SHA,
            "c4b1e5h2_sha256": H2_SHA,
        },
        "cross_carrier_incidence": {
            "repeated_factor_group_count": 3,
            "repeated_factor_context_count": 10,
            "actual_geometric_prime_cluster_count": 10,
            "all_10_repeated_contexts_are_pairwise_distinct_within_their_common_base_factor_groups": True,
            "no_distinctness_inference_uses_context_local_prime_id_inequality": True,
            "incidence_method": "EXACT_CONTRACTION_TO_THE_C1_IRREDUCIBLE_BASE_FACTOR_PLUS_EXPLICIT_LOW_DEGREE_POLYNOMIAL_WITNESSES_FOR_EVERY_CROSS_CARRIER_PAIR",
            "group_rows": group_rows,
        },
        "strict_prime_tame_parity_after_incidence": {
            "geometric_prime_cluster_count": 10,
            "zero_formal_parity_cluster_count": zero_parity,
            "nonzero_formal_parity_cluster_count_requiring_residue_field_reduction": nonzero_parity,
            "unique_factor_strict_prime_context_count": 18,
            "unique_factor_nonzero_formal_parity_context_count": unique_nonzero,
            "total_targeted_strict_prime_residue_field_squareclass_rows_for_C4B2B": unique_nonzero + nonzero_parity,
        },
        "exact_consequence": {
            "C4A_repeated_factor_cross_carrier_geometric_incidence_materialized": True,
            "all_repeated_factor_contexts_remain_single_carrier_geometric_prime_contexts": True,
            "all_10_repeated_factor_contexts_remain_nonzero_formal_parity": True,
            "all_18_unique_factor_contexts_remain_nonzero_formal_parity": True,
            "C4B2B_target_strict_prime_count": 28,
            "nonzero_parity_is_not_declared_nonsquare": True,
            "combined_tame_residue_squareclasses_audited_on_every_strict_prime": False,
            "offboundary_codimension_one_residue_cancellation_verified": False,
            "unramifiedness_verified": False,
        },
        "next_exact_leaf": "V91C1X_R5B3B3C4B2B_STRICT_PRIME_TARGETED_RESIDUE_FIELD_SQUARECLASS_REDUCTION",
        "next_exact_step": "reduce the exact combined odd-carrier representatives in the residue fields of the 28 now geometrically separated strict-prime contexts; do not infer nonsquare from nonzero formal parity",
        "credit_firewall": {
            "authority_promotion": False,
            "hostile_audit_credit": False,
            "h2_fixedness_credit": False,
            "marked_brauer_image_credit": False,
            "genuine_full_surface_h2_mu2_lift_credit": False,
            "offboundary_cancellation_credit": False,
            "unramifiedness_credit": False,
            "stage33_close_credit": False,
            "stage33_release_credit": False,
            "theorem_credit": False,
            "receiver_credit": False,
            "endpoint_credit": False,
            "merge_allowed": False,
        },
    }
    cert["canonical_sha256"] = csha(cert)
    return cert


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()
    cert = build_certificate()
    text = json.dumps(cert, indent=2, sort_keys=True) + "\n"
    if args.write:
        OUT.write_text(text, encoding="utf-8")
        p = cert["strict_prime_tame_parity_after_incidence"]
        print(json.dumps({
            "success": True,
            "marker": cert["candidate"],
            "repeated_contexts": cert["cross_carrier_incidence"]["repeated_factor_context_count"],
            "geometric_prime_clusters": cert["cross_carrier_incidence"]["actual_geometric_prime_cluster_count"],
            "zero_parity_clusters": p["zero_formal_parity_cluster_count"],
            "nonzero_parity_clusters": p["nonzero_formal_parity_cluster_count_requiring_residue_field_reduction"],
            "c4b2b_target_strict_primes": p["total_targeted_strict_prime_residue_field_squareclass_rows_for_C4B2B"],
            "certificate_sha256": cert["canonical_sha256"],
            "next_exact_leaf": cert["next_exact_leaf"],
        }, sort_keys=True))
        return
    if not OUT.exists():
        raise SystemExit(f"missing materialized certificate: {OUT}")
    current = json.loads(OUT.read_text(encoding="utf-8"))
    if current != cert:
        raise SystemExit("materialized C4B2A certificate differs from exact rebuild")
    print(cert["canonical_sha256"])


if __name__ == "__main__":
    main()
