#!/usr/bin/env python3
from fractions import Fraction
import ast
import hashlib
import json
import pathlib
import urllib.error
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET

ROOT = pathlib.Path(__file__).resolve().parent
UPSTREAM_URL = (
    "https://raw.githubusercontent.com/MichaelStollBayreuth/Verification/"
    "51233ed5ef2bf228fac9416c66db9adc0ebcaadd/Cuboids/cuboids.magma"
)
UPSTREAM_BLOB = "0422b69847f2afb97cb7b3ed02ebef91279f61b1"
SKIP_START = "// Genus 3 hyperelliptic curves of degree 8"
SKIP_END = "// Set up the intersection pairing"
PIC_MARKER = "// Construct the Picard group (assuming it is generated by the known curves)"
MAGMA_URL = "https://magma.maths.usyd.edu.au/xml/calculator.xml"
MAGMA_REFERER = "https://magma.maths.usyd.edu.au/calc/"
INDLIST = [
    1,2,3,4,5,6,7,9,10,11,12,13,14,15,17,18,19,20,21,22,23,25,26,27,29,
    33,34,35,37,38,41,45,49,53,69,
    93,94,95,96,97,98,99,101,102,103,104,105,106,107,109,110,111,113,
    117,118,119,120,121,125,126,127,129,133,135,
]
assert len(INDLIST) == 64 and len(set(INDLIST)) == 64


def git_blob_sha(data: bytes) -> str:
    header = b"blob " + str(len(data)).encode("ascii") + b"\0"
    return hashlib.sha1(header + data).hexdigest()


def fetch_bytes(url: str, timeout: int = 60) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "perfect-cuboid-stage32/1.5"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        if resp.status != 200:
            raise RuntimeError(f"HTTP {resp.status} from {url}")
        return resp.read()


def parse_magma_xml(raw: str) -> list[str]:
    root = ET.fromstring(raw)
    lines = []
    for result in root.findall(".//results"):
        for line in result.findall(".//line"):
            lines.append("".join(line.itertext()))
    return lines


def post_magma(code: str, part: int) -> list[str]:
    data = urllib.parse.urlencode({"input": code}).encode("utf-8")
    req = urllib.request.Request(
        MAGMA_URL,
        data=data,
        headers={
            "Content-Type": "application/x-www-form-urlencoded",
            "Accept": "text/html, application/xml, application/xhtml+xml",
            "Referer": MAGMA_REFERER,
            "User-Agent": "perfect-cuboid-stage32/1.5",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=75) as resp:
            raw = resp.read().decode("utf-8", errors="replace")
            status = resp.status
    except urllib.error.HTTPError as exc:
        diagnostic = exc.read().decode("utf-8", errors="replace")
        (ROOT / f"magma-core-export-part{part}-http-error.txt").write_text(
            f"HTTP {exc.code} {exc.reason}\n{diagnostic}\n", encoding="utf-8"
        )
        raise
    (ROOT / f"magma-core-export-part{part}.xml").write_text(raw, encoding="utf-8")
    lines = parse_magma_xml(raw)
    stdout = "\n".join(lines) + ("\n" if lines else "")
    (ROOT / f"magma-core-export-part{part}.txt").write_text(stdout, encoding="utf-8")
    if status != 200 or f"STAGE32_EXPORT_END|{part}" not in lines:
        raise SystemExit(f"Magma core export part {part} incomplete")
    if any(x in stdout for x in ("Runtime error", "Internal error", "User error", "Assertion failed")):
        raise SystemExit(f"Magma core export part {part} reported an error")
    return lines


def invert_matrix(a: list[list[int]]) -> tuple[list[list[Fraction]], Fraction]:
    n = len(a)
    m = [
        [Fraction(x) for x in a[i]] + [Fraction(int(i == j)) for j in range(n)]
        for i in range(n)
    ]
    det = Fraction(1)
    sign = 1
    for col in range(n):
        pivot = next((r for r in range(col, n) if m[r][col]), None)
        if pivot is None:
            raise SystemExit("basis Gram matrix is singular")
        if pivot != col:
            m[col], m[pivot] = m[pivot], m[col]
            sign *= -1
        p = m[col][col]
        det *= p
        m[col] = [x / p for x in m[col]]
        for r in range(n):
            if r == col:
                continue
            q = m[r][col]
            if q:
                m[r] = [m[r][c] - q * m[col][c] for c in range(2*n)]
    inv = [row[n:] for row in m]
    return inv, det * sign


def mul_row(row, matrix):
    n = len(matrix)
    return [sum(Fraction(row[k]) * matrix[k][j] for k in range(n)) for j in range(n)]


def integral_row(row, label: str) -> list[int]:
    if any(x.denominator != 1 for x in row):
        raise SystemExit(f"non-integral coordinates for {label}")
    return [int(x) for x in row]


upstream = fetch_bytes(UPSTREAM_URL)
actual_blob = git_blob_sha(upstream)
if actual_blob != UPSTREAM_BLOB:
    raise SystemExit(f"upstream blob mismatch: expected {UPSTREAM_BLOB}, got {actual_blob}")
text = upstream.decode("utf-8")
try:
    i0 = text.index(SKIP_START)
    i1 = text.index(SKIP_END, i0 + len(SKIP_START))
    i2 = text.index(PIC_MARKER, i1 + len(SKIP_END))
except ValueError as exc:
    raise SystemExit(f"pinned source markers missing/out of order: {exc}")

head = text[:i0]
pairing_block = text[i1 + len(SKIP_END):i2]
base = "SetColumns(0);\nquick := true;\n" + head + "\n" + pairing_block
ind_magma = "[" + ",".join(str(x) for x in INDLIST) + "]"

all_rows: dict[int, list[int]] = {}
hpair = None
for part, (lo, hi) in enumerate(((1,70),(71,140)), start=1):
    suffix = f'''
indlist32 := {ind_magma};
assert #indlist32 eq 64;
assert #Cs eq 92 and #pts eq 48 and bdim eq 140;
printf "STAGE32_EXPORT_BEGIN|{part}|{lo}|{hi}\\n";
'''
    if part == 1:
        suffix += '''
hpair32 := [];
for k in [1..64] do
  j := indlist32[k];
  Append(~hpair32, j le #Cs select Degree(Cs[j]) else 0);
end for;
printf "STAGE32_EXPORT_HPAIR|%o\\n", hpair32;
'''
    suffix += f'''
for j in [{lo}..{hi}] do
  printf "STAGE32_EXPORT_X|%o|%o\\n", j,
      [pairingmat[j, indlist32[k]] : k in [1..64]];
end for;
printf "STAGE32_EXPORT_END|{part}\\n";
'''
    lines = post_magma(base + suffix, part)
    for line in lines:
        if line.startswith("STAGE32_EXPORT_HPAIR|"):
            value = ast.literal_eval(line.split("|",1)[1])
            if not isinstance(value, list) or len(value) != 64:
                raise SystemExit("bad H-pairing export")
            hpair = [int(x) for x in value]
        elif line.startswith("STAGE32_EXPORT_X|"):
            _, js, vecs = line.split("|",2)
            j = int(js)
            value = ast.literal_eval(vecs)
            if not isinstance(value, list) or len(value) != 64:
                raise SystemExit(f"bad cross-pairing row {j}")
            all_rows[j] = [int(x) for x in value]

if hpair is None or set(all_rows) != set(range(1,141)):
    raise SystemExit("incomplete two-part Picard export")
cross = [all_rows[j] for j in range(1,141)]
gram = [cross[j-1] for j in INDLIST]
if any(gram[i][j] != gram[j][i] for i in range(64) for j in range(64)):
    raise SystemExit("basis Gram matrix is not symmetric")

inv, det = invert_matrix(gram)
known = []
for j, x in enumerate(cross, start=1):
    known.append(integral_row(mul_row(x, inv), f"known class {j}"))
h = integral_row(mul_row(hpair, inv), "hyperplane")

# The chosen upstream indlist must literally become the standard basis.
for k, j in enumerate(INDLIST):
    expected = [0]*64
    expected[k] = 1
    if known[j-1] != expected:
        raise SystemExit(f"indlist class {j} did not become basis vector {k+1}")

def pairing(u, v):
    return sum(u[i] * gram[i][j] * v[j] for i in range(64) for j in range(64))

if pairing(h, h) != 16:
    raise SystemExit(f"wrong hyperplane square: {pairing(h,h)}")
for j in range(140):
    reconstructed = [pairing(known[j], known[k-1]) for k in INDLIST]
    if reconstructed != cross[j]:
        raise SystemExit(f"cross-pairing reconstruction failed at class {j+1}")

core_payload = {
    "schema": "STAGE32_PICARD_CORE_INDLIST_V1",
    "source": {
        "repo": "MichaelStollBayreuth/Verification",
        "commit": "51233ed5ef2bf228fac9416c66db9adc0ebcaadd",
        "file": "Cuboids/cuboids.magma",
        "git_blob_sha1": actual_blob,
    },
    "rank": 64,
    "h2": 16,
    "known_curve_count": 92,
    "node_count": 48,
    "known_class_count": 140,
    "basis_kind": "upstream primitive indlist known-class basis",
    "basis_known_indices_1based": INDLIST,
    "basis_gram": gram,
    "hyperplane": h,
    "known_classes": known,
    "raw_cross_pairings_with_basis": cross,
    "basis_gram_determinant": int(det) if det.denominator == 1 else str(det),
}
canonical = json.dumps(core_payload, separators=(",", ":"), sort_keys=True).encode("utf-8")
core_payload["canonical_sha256_without_this_field"] = hashlib.sha256(canonical).hexdigest()
(ROOT / "picard-core.json").write_text(
    json.dumps(core_payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
)
print(json.dumps({
    "success": True,
    "schema": core_payload["schema"],
    "rank": 64,
    "known_class_count": 140,
    "h2": pairing(h,h),
    "basis_gram_determinant": core_payload["basis_gram_determinant"],
    "core_sha256": core_payload["canonical_sha256_without_this_field"],
    "upstream_blob": actual_blob,
}, sort_keys=True))
